### ISSUE TITLE
[Bug]: Dynamic slides not scrolling

### ISSUE THREAD

**Issue by gnllucena** [davidjerleke/embla-carousel#1019]
### Which variants of Embla Carousel are you using?

- [X] embla-carousel **(Core)**
- [X] embla-carousel-react
- [ ] embla-carousel-vue
- [ ] embla-carousel-svelte
- [ ] embla-carousel-autoplay
- [ ] embla-carousel-auto-scroll
- [ ] embla-carousel-solid
- [ ] embla-carousel-auto-height
- [ ] embla-carousel-class-names
- [ ] embla-carousel-fade
- [ ] embla-carousel-docs **(Documentation)**
- [ ] embla-carousel-docs **(Generator)**

### Steps to reproduce

https://github.com/user-attachments/assets/1b4180af-326c-4a0e-8465-7cadbc413ead

The bug occurs when I try to scroll slides using `emblaApi?.scrollNext()`. 

It’s important to note that those slides are dynamically managed using React’s `useState` hook to allow new slides to be added via a button click

steps to reproduce:

`git clone https://github.com/gnllucena/embla-dynamic-slides`
`cd embla-dynamic-slides`
`npm install`
`npm run dev`

### Expected Behavior

The slides should scroll

### Additional Context

While searching the issues I've stumbled upon this piece of code to re init the carousel when new slides are added, unfortunately it's not working for me:

```
  useEffect(() => {
    if (emblaApi) {
      emblaApi.reInit()
    }
  }, [emblaApi, slides])
```

### What browsers are you seeing the problem on?

Chrome, Microsoft Edge

### Version

8.3.0

### CodeSandbox

https://github.com/gnllucena/embla-dynamic-slides

### Before submitting

- [X] I've made research efforts and searched the documentation
- [X] I've searched for existing issues
- [X] I agree to follow this project's Contributing Guidelines for bug reports

**Comment by davidjerleke** [comment]
@gnllucena thanks for your bug report. If you want help faster, please create a CodeSandbox instead. You may fork any of the examples on the documentation website and change it so it reproduces the problem. Please don’t forget to strip it from all unnecessary details so I can debug effectively.

**Comment by gnllucena** [comment]
There you go, @davidjerleke:

https://codesandbox.io/p/sandbox/embla-carousel-generator-react-forked-8dh3f8?workspaceId=22c95318-cd64-4dd2-b59d-9cfa7b818618

**Comment by davidjerleke** [comment]
@gnllucena I don't think this is a bug but rather the way you have markup in your states. [This works](https://codesandbox.io/p/sandbox/embla-carousel-generator-react-forked-yv2z69) as expected.

**Comment by gnllucena** [comment]
hey, @davidjerleke! 

Yeah, I do have markup in my state because they’re supposed to be different components.

My use case is: depending on the products you choose to buy, a different checkout experience is presented to you. Embla controls that workflow, with different components at each step of the carousel.

I’ve created a new sandbox detailing that: https://codesandbox.io/p/sandbox/embla-carousel-generator-react-forked-8dh3f8?file=%2Fsrc%2Fjs%2FEmblaCarousel.tsx%3A68%2C43&workspaceId=22c95318-cd64-4dd2-b59d-9cfa7b818618

(For the sake of simplicity, the slides all look the same, but in my case, they’re wildly different. Hence, I don’t think your example fits the problem I'm describing.)

In the first step, there’s only one slide on the carousel. If you click `Move to next` or drag the slide, you’ll notice that there are no other slides:

https://github.com/user-attachments/assets/dd7b6676-f0bc-41ed-9023-5aeac6d8f91d

If you click on `Add old Product`, React adds two new slides into the carousel. You’ll notice that the `Move to next` button does not work, BUT if you drag the slides, it actually works! Even weirder: if you click on Move to next on the second slide, it also works:

https://github.com/user-attachments/assets/8d95da16-2738-48e9-bf01-6bfcac18cee6

if you think that's not a bug, do you have any suggestion on how to have very different dynamic slides on Embla?

**Comment by davidjerleke** [comment]
React adds two new slides into the carousel. You’ll notice that the Move to next button does not work, BUT if you drag the slides, it actually works! Even weirder: if you click on Move to next on the second slide, it also works.

@gnllucena I think this is expected, because my understanding of React is that you shouldn't use `useState`'s with markup. They're supposed to be isolated states containing either primitive data types or complex like objects or arrays. They should not be responsible for rendering. As you can see the `scrollNext` is the functionality that never works in your code examples, that's the common thread. Because it's added into the setState where it shouldn't be.

With that said, Embla doesn't restrict you from rendering different children, it allows for any children. Se a [modified sandbox](https://codesandbox.io/p/sandbox/embla-carousel-generator-react-forked-4t2k6h) for one way to solve it. Another way would be to simply pass children to the `EmblaCarousel` component and map the children with a slide wrapper but other than that just render the child content as is, which you can [read about here](https://stackoverflow.com/questions/49496906/react-mapping-children-of-a-parent-component).

This isn't a bug because I think you're using React as it's not intended to be used when putting markup in your states.

**Comment by gnllucena** [comment]
I was able to make dynamic scroll work based on your example. thanks for the help, @davidjerleke
