### ISSUE TITLE
[Bug]: slidesInView method returns invisible items

### ISSUE THREAD

**Issue by erkanaltinors** [davidjerleke/embla-carousel#1088]
### Which variants of Embla Carousel are you using?

- [ ] embla-carousel **(Core)**
- [X] embla-carousel-react
- [ ] embla-carousel-vue
- [ ] embla-carousel-svelte
- [ ] embla-carousel-autoplay
- [ ] embla-carousel-auto-scroll
- [ ] embla-carousel-solid
- [ ] embla-carousel-auto-height
- [ ] embla-carousel-class-names
- [ ] embla-carousel-fade
- [ ] embla-carousel-docs **(Documentation)**
- [ ] embla-carousel-docs **(Generator)**

### Steps to reproduce

I use embla-carousel-react with Shadcn's carousel component. I need nextScrollSnap (similar to previousScrollSnap method) method so that i can get next visible item in carousel when next button  pressed. i wanted to use slidesInView method to achieve next scroll snap item but it returns different sized array for each next button press. You can see results in console.

[Stackblitz](https://stackblitz.com/edit/stackblitz-starters-ycnzcffc?file=components%2Fui%2Fcarousel.tsx)

### Expected Behavior

slidesInView method returns 1 more item if next/previous button pressed before scroll animation ends.
nextScrollSnap method would help me to use it like previousScrollSnap method.

### Additional Context

I have also tried...

### What browsers are you seeing the problem on?

Chrome

### Version

v8.5.1

### Before submitting

- [X] I've made research efforts and searched the documentation
- [X] I've searched for existing issues
- [X] I agree to follow this project's Contributing Guidelines for bug reports

**Comment by davidjerleke** [comment]
@erkanaltinors thanks for your question. I’m confused, the title suggests there’s something wrong with `slidesInView` (which shouldn’t be the case because Embla uses IntersectionObserver under the hood) but in your description it seems like you want to know which slide is next in turn?

If that’s the case, please move your question to a [discussion](https://github.com/davidjerleke/embla-carousel/discussions/new?category=help) in the help category instead. This isn’t a bug.

Thanks for understanding.

**Comment by erkanaltinors** [comment]
hi @davidjerleke , slidesInView method returns 1 more item if next button pressed before scroll animation ends. You can see the log if next button several times quickly.

**Comment by erkanaltinors** [comment]
[Discussion](https://github.com/davidjerleke/embla-carousel/discussions/1089) added. Closing this issue. Thanks @davidjerleke

**Comment by davidjerleke** [comment]
@erkanaltinors this is expected, because during transition, all slides with any part visible are considered in view. That’s how IntersectionObserver works (which is a native browser API).

If you want slides to be considered in view only when the full slide is in view, set the inViewThreshold option to 0.99.
