### ISSUE TITLE
[Bug]: "Settle" event has a noticeable delay

### ISSUE THREAD

**Issue by yishayhaz** [davidjerleke/embla-carousel#1097]
### Which variants of Embla Carousel are you using?

- [X] embla-carousel-react

### Steps to reproduce

The bug occurs when I listen to the "Settle" event

### Expected Behavior

I expect it to be instantaneous 

### Additional Context

Not customizing neither dragFree not transitions
<img width="776" alt="image" src="https://github.com/user-attachments/assets/f3ced1b5-9851-4a0b-9c06-6144bc21d3ac" />

### What browsers are you seeing the problem on?

All browsers

### Version

8.5.1

### Before submitting

- [X] I've made research efforts and searched the documentation
- [X] I've searched for existing issues
- [X] I agree to follow this project's Contributing Guidelines for bug reports

**Comment by davidjerleke** [comment]
Please don’t just tick the “I’ve made research efforts” checkbox. This is [expected](https://www.embla-carousel.com/api/events/#settle).

**Comment by yishayhaz** [comment]
@davidjerleke Thank you for the quick response.

I have made a quick research, and came across the documentation stating that it's expected - I've attached a screenshot in my bug report. and it surely feels like a bug, even if you anticipate it. you must agree.

Are there any possible workarounds?

**Comment by davidjerleke** [comment]
@yishayhaz thanks.

> it surely feels like a bug, even if you anticipate it

The `settle` event will fire when the carousel has stopped animating **completely**. The last part of the scrolling could be a matter of a moving pixel or sub-pixels, and that's why it takes longer than you might expect. I understand that it might not be desired for your use case, but "Feels like" doesn't necessarily mean that it actually is a bug. This is by design.

> Are there any possible workarounds?

Please check this out:

- https://github.com/davidjerleke/embla-carousel/discussions/738#discussioncomment-8404744

**Comment by yishayhaz** [comment]
Thank you! this is perfect.
