### ISSUE TITLE
Non-visible slides when using CSS grid in combination with `loop: true`

### ISSUE THREAD

**Issue by klipstein** [davidjerleke/embla-carousel#285]
### Bug is related to

- [x] embla-carousel (core package)

### Embla Carousel version

- v6.2.0

### Describe the bug

When CSS grid (as described [here](https://www.embla-carousel.com/guides/slide-container/#using-css-grid)) is used in combination with `loop: true`, the `left` offset of the last or first slide is not properly calculated and it leads to not showing the first/last card inside the carousel.

The calculation here is correct for flex-box: https://github.com/davidjerleke/embla-carousel/blob/master/packages/embla-carousel/src/components/SlideLooper.ts#L49-L63

But when `display: grid` is used for the `embla__container` the value `left` needs to be set relative to each slide/card instead of the container width (+ gaps).

### CodeSandbox

https://codesandbox.io/s/embla-carousel-loop-vanilla-forked-4b75xf?file=/package.json

Or as standalone example: https://4b75xf.csb.app/

### Steps to reproduce

1. Open https://4b75xf.csb.app/ (Carousel with loop: true and CSS Grid)
2. Last card is shown on the left
3. Click on previous button
4. Now the first card is not shown on the right

### Expected behavior

That the last / first card is shown when looped using CSS grid.

#### Initial Load: missing last card
<img width="707" alt="Screenshot 2022-02-21 at 17 54 48" src="https://user-images.githubusercontent.com/158866/154998171-03819dae-d714-4ed5-ab52-3a7992342eec.png">

#### Clicking on previous button: first card is not shown
<img width="711" alt="Screenshot 2022-02-21 at 17 54 55" src="https://user-images.githubusercontent.com/158866/154998246-08f512e9-b91c-4734-95fe-6b70cbd05f24.png">

**Comment by davidcetinkaya** [comment]
Hi @klipstein,
Thank you for reporting this problem and a clear bug report.

I've been meaning to change the transition unit from `%` to `px` for a while. That **might** solve this problem because using absolute units won't cause problems with relative positioning like this bug.

The sole reason why I went with Embla using `left/top` over `transform: translate()` when shifting slide positions (when loop is activated), is because Safari is freaking out when transforming slides with the `%` unit. The `%` transform calculations in Safari isn't precise so it's rendering unwanted 1-5 px glitches between slides when shifting positions (this isn't an issue with other browsers though). So when I built this, I went with the left/top properties because I wanted the transition unit to be `%`. Working with pixels instead, which is an absolute unit, Safari is behaving correctly so therefore it might be worth migrating to `px` transitions.

A side note. If you're using `grid-gap` to add spacing between your slides you won't have a gap between the first and last slide. You'll need to add margin to the last slide or similar to achieve this.

This issue won't be my highest priority right now because as you mentioned it's possible to use flexbox instead. The following issue:

- #281

...has the highest priority because it's very time consuming and I have to get rid of that.

Best,
David

**Comment by klipstein** [comment]
This issue is rather an edge-case and I mostly wanted to document it (until potentially fixed) in case someone else stumbles upon it.

**Comment by davidcetinkaya** [comment]
@klipstein, very much appreciated. I’ll see if changing unit to `px` solves the problem when I’m working on it.

Cheers,
David

**Comment by davidcetinkaya** [comment]
@klipstein I’m working on Embla v7 now and this bug will be solved there.

**Comment by davidjerleke** [comment]
Hi @klipstein,

If you're interested: [v7.0.0-rc01](https://github.com/davidjerleke/embla-carousel/releases/tag/v7.0.0-rc01) has been released. Feel free to try it out and confirm if the bug is gone if you want.

Cheers,
David

**Comment by davidjerleke** [comment]
@klipstein thank you for your swift response and testing it 👍. The missing gap between the last and the first slide is expected because setting `gap` in CSS only applies gap between items and not to the end. Embla won't interfere with or modify the CSS you choose to add spacing and that's why this is something the user has to solve.

Again, thanks for confirming that the bug is gone.

Cheers,
David

**Comment by davidjerleke** [comment]
Released with [v7](https://github.com/davidjerleke/embla-carousel/releases/edit/v7.0.0).
