### ISSUE TITLE
⭐ v7

### ISSUE THREAD

**Issue by davidjerleke** [davidjerleke/embla-carousel#298]
# v7

## New features

- [x] #322
- [x] #329
- [x] #17 
- [x] #307 
- [x] #305
- [x] #327
- [x] #330

## Changes
- [x] #331
- [x] #60 - **The transform unit will change**: From `%` to `px`. As a result, the `position: relative` style on the slides needed for loop carousels to work, will be unnecessary.

## Bugfixes
- [x] #285
- [x] #317

## Breaking Changes
- [x] #327

## Features that will be removed
- [x] Pseudo options

**Comment by knenkne** [comment]
Would be also great to resolve `react` up to **18** in `package.json`, to not fight with the legacy peer deps things 😅

**Comment by davidcetinkaya** [comment]
Hi @knenkne,

Thank you for your input. React 18 support has been added to the upcoming version 7. You can [track the progress](https://github.com/davidcetinkaya/embla-carousel/issues/298#issue-1197224361) here.

**Comment by deltasierra96** [comment]
Hi, @davidcetinkaya 

Would there be a possibility of adding responsive functionality that would contain a responsive option? As much as I love how responsive Embla is, manipulating options such as how many slides to show and/or scroll depending on viewport size is quite cumbersome - at least to my understanding of the `embla.on('reInit')` and `embla.on('resize')` methods.

I've went around in circles trying to overcome this issue when referencing your "infinite" example on Codepen when trying to make an API request with the following code.

`const [pageCount, setPageCount] = useState(1);
  const [hasMoreToLoad, setHasMoreToLoad] = useState(true);
  const [prevBtnEnabled, setPrevBtnEnabled] = useState(false);
  const [nextBtnEnabled, setNextBtnEnabled] = useState(false);
  const [slidesInView, setSlidesInView] = useState([]);

  const [viewportRef, embla] = useEmblaCarousel({
    align: 'start',
    inViewThreshold: 0,
    slidesToScroll: slidesToScroll
  });

  const loadingMore = useInfiniteScroll(embla, slides, hasMoreToLoad);
  const scrollPrev = useCallback(() => embla && embla.scrollPrev(), [embla]);
  const scrollNext = useCallback(() => embla && embla.scrollNext(), [embla]);
  const slidesToScroll = 8;
  const pageLimit = 4;

  const onSelect = useCallback(() => {
    if (!embla) return;
    // Needed to apply active index to slide for tailwind conditional classes.
    // However if containScroll is set to keep or trim, this functionality bugs out
    // on new API requests.
    setSlidesInView(embla.slidesInView(true));
    setPrevBtnEnabled(embla.canScrollPrev());
    setNextBtnEnabled(embla.canScrollNext());
  }, [embla]);

  const fetchMoreResults = useCallback(async () => {
    if (!loadingMore) return;
    const data = await fetch(`${requests.fetchComedyMovies}&page=${pageCount}`);
    const movies = await data.json();

    setSlides((currentSlides) => {
      if (currentSlides.length === slidesToScroll || pageCount === pageLimit) {
        setHasMoreToLoad(false);
        return currentSlides;
      }
      setPageCount(pageCount + 1);
      return [...currentSlides, ...movies.results];
    });
  }, [loadingMore, setSlides, pageCount]);

  useEffect(() => {
    fetchMoreResults();
  }, [fetchMoreResults]);

  useEffect(() => {
    if (!embla) return;
    embla.on('select', onSelect);
    embla.on('reInit', onSelect);
    onSelect();
  }, [embla, onSelect]);`

If you could enlighten me on such a remedy to this issue without the need of a new feature request, I'd be in your debt massively.

Many thanks.

**Comment by davidcetinkaya** [comment]
Hi @deltasierra96,

Have you tried [this approach]( https://www.embla-carousel.com/api/options/#pseudo-options)  to set different options for different breakpoints?

Best,
David

**Comment by AhmedAbdulrahman** [comment]
Hi @davidjerleke, 
I see sometimes my slider gets negative translate on mobile on initial load (using in vanilla)? is this a bug that you are solving or something related to CSS from my end?

![image](https://user-images.githubusercontent.com/10485129/167070859-7e79c14d-0bec-400e-a8fc-bf73a6684c89.png)

**Comment by davidjerleke** [comment]
Hi @AhmedAbdulrahman,

It could be related to your CSS. But it’s impossible to say without any context. If you want me to look into it please create a CodeSandbox with your setup. Please create a separate bug report for this because it’s not related to v7.

Best,
David

**Comment by AhmedAbdulrahman** [comment]
@davidjerleke I have created a new [issue](https://github.com/davidjerleke/embla-carousel/issues/310) with CodeSandbox link

**Comment by deltasierra96** [comment]
> Hi @deltasierra96,
> 
> Have you tried [this approach](https://www.embla-carousel.com/guides/breakpoints/#changing-options) to set different options for different breakpoints?
> 
> If it's an option for you, please read [this](https://github.com/davidcetinkaya/embla-carousel/issues/302#issuecomment-1101734829) too because the docs needs an update on that part.
> 
> Also, please note that this feature in v7:
> 
> > * [x]  **New option value:** `slidesToScroll: 'auto'` - Embla will automatically group slides for you depending on how many slides fit within the viewport. And not just upon initialization, it will do that on every resize too.
> 
> …will make the `slidesToScroll` code in your example redundant. Embla will automatically group slides for you, both when it’s initialized and when resized.
> 
> Best, David

Hi again, David

Thanks for the reply and I apologise for the lateness of my own.

I ended up sorting the slidesToScroll issue with your recommendation to use the content pseudo selector - it works perfectly with my current implementation, but there's just one major issue I'm having relating to the infinite slide functionality.

If the initial slides array is not the same length as the next array, the infinite scroll doesn't respect the slide limit and will continue to generate slides well beyond the initial limit of 20, even in your [example](https://codesandbox.io/s/embla-carousel-infinite-scroll-react-forked-qww2c1)

Currently with my implementation in[ this sandbox,](https://codesandbox.io/s/embla-tailwind-api-infinite-scroll-rprqz2) the slider is initialised with 5 results and a minimum limit of 20 and API page limit of 4 set here `if (currentSlides.length === 20 || pageCount === pageLimit)`, the dragging of the slide would still trigger an API call, appending another 20 results and return the incorrect indexes of the slides that are in view which messes up the opacity value of each slide and still allow the user to drag the slides off screen, creating a blank void.

Is there anyway to set a minimum slide limit AND a maximum page call limit to the API, so that the slider drag and/or arrow actions are disabled if this minimum amount is not met or the API calls meet their page limit, whilst also pertaining the "snap to end" functionality for the last item?

I really do apologise if this is hard to understand from my poorly written English.

**Comment by davidjerleke** [comment]
Hi @deltasierra96,

Would you mind creating a discussion and copy and paste your [comment](https://github.com/davidjerleke/embla-carousel/issues/298#issuecomment-1120247808)? Because I don’t think this conversation is relevant to this issue.

Best,
David

**Comment by deltasierra96** [comment]
> Hi @deltasierra96,
> 
> Would you mind creating a discussion and copy and paste your [comment](https://github.com/davidjerleke/embla-carousel/issues/298#issuecomment-1120247808) to it? Because I don’t think this conversation is relevant to this issue.
> 
> Best, David

Will do. If you're able to delete these comments, then please do so. I apologise for high jacking the thread.

Thanks,
Dylan

**Comment by davidjerleke** [comment]
Hi @jordanpacheco1,

You can follow the [progress here](https://github.com/davidjerleke/embla-carousel/issues/298#issue-1197224361). A checked checkbox means that the task is complete. But I can't give an estimate because I'm maintaining this library on my unpaid spare time. So I can't give any guarantees. Thank you for understanding.

Best,
David

**Comment by brniamut** [comment]
@davidjerleke Hey David!, if you need any help let me know. The organisation I work is kind of needs the update and I have the time to work on the library if needed. If you have a more detailed list, or a task I can work on, let me know.

**Comment by davidjerleke** [comment]
Hi @brniamut,

Thank you and very nice of you to offer help. I only have one thing left to finish actually: Because I'm introducing the breakpoints option, Embla will internally check if any options have changed depending on the media query you provide like so (when the window is resized):

```ts
// VanillaJS
const embla = EmblaCarusel(emblaNode, {
  loop: false,
  breakpoints: {
    '(min-width: 768px)': { loop: true }
  }
});

// ReactJS
const [emblaRef, emblaApi] = useEmblaCarousel({
  loop: false,
  breakpoints: {
    '(min-width: 768px)': { loop: true }
  }
});
```
 
Note that plugins will also accept breakpoint options. For this to work I'm writing an options diff check function which will be used to determine if any options have changed. That's actually the only part left to do so getting close to wrapping up now. I'll add CodeSandboxes soon so I would very much appreciate if you would like to test it so we can find any critical bugs before the release. I'll let you know when it's ready.

Best,
David

**Comment by brniamut** [comment]
@davidjerleke at you service!

**Comment by davidjerleke** [comment]
@brniamut I've added CodeSandboxes to the [original post](https://github.com/davidjerleke/embla-carousel/issues/298#issue-1197224361) now 👍.

**Comment by davidjerleke** [comment]
Hej @ketijakrista,

I don't have much left to fix. But I can't [give any guarantees](https://github.com/davidjerleke/embla-carousel/issues/298#issuecomment-1121405519). I don't want to rush things because that's how you introduce a lot of bugs. If you want to speed up the process you can test the current state of v7. Both the new features and existing features. CodeSandboxes are to be found in the [original post](https://github.com/davidjerleke/embla-carousel/issues/298#issue-1197224361).

Kindly,
David

**Comment by MaxDesignFR** [comment]
Hi @davidjerleke 

About the documentation, it seems Embla carrousel does take into calculation hidden slides, which results in errors. Here is a very simple example I forked with 2 hidden slides: https://codesandbox.io/s/embla-carousel-default-vanilla-forked-tsu2q2?file=/index.html

Should I open a bug report for this, or maybe it could be mentioned in the docs? We can still manipulate the slides, but from what I've experienced, removing slides from the document flow such as `display:none` don't work, we actually need to remove them from the DOM entirely. 

That's your call, the concise docs is actually really well made and easy to navigate, helped me give Embla a serious shot!

**Comment by davidjerleke** [comment]
Hello folks,

I’m getting real close to a release candidate so stay tuned. If anyone knows how to solve this:

- [StackOverflow question](https://stackoverflow.com/questions/72627489/how-to-include-external-dependencies-in-umd-bundle-with-rollup)

Please let me know. It only affects CDN users but it’s still needed before a stable v7 release.

Cheers,
David

**Comment by madebyfabian** [comment]
Hi there,

I am currently evaluating nearly all react sliders and yours is still the best. So I would love to use it, but I need especially the responsive feature in v7.
Is there anything I could do to support you releasing v7? 

Best,
Fabian

**Comment by davidjerleke** [comment]
Hi @madebyfabian,

Thank you very much for offering your help. I have some small things left to do to wrap v7 up. So maybe it's not optimal to join at this stage. But, as soon as the release candidate is out, I'm going to need help with the following:

- Testing it so we can find bugs and solve them.
- Improve the documentation.

Cheers,
David

**Comment by davidjerleke** [comment]
Hello all,

I've published a release candidate for v7. Please read the [release details](https://github.com/davidjerleke/embla-carousel/releases/tag/v7.0.0-rc01). Any information regarding the new features can be found in each individual issue listed in the release details.

Cheers,
David

**Comment by davidjerleke** [comment]
Hi all,

If any of you guys have tried the release candidate I would appreciate feedback if you’ve encountered any bugs, or if you’ve tried it and it was working as expected because that’s also useful feedback.

Thanks in advance.

Best,
David

**Comment by gruberro** [comment]
I've tested the latest release candidate, all worked as expected 🙌 .

**Comment by davidjerleke** [comment]
@MaxDesignFR and @gruberro thank you for the feedback.

@MaxDesignFR, would you mind sharing what options and CSS you’re using. Or even better, a CodeSandbox with the full setup?

Best,
David

**Comment by MaxDesignFR** [comment]
> @MaxDesignFR and @gruberro thank you for the feedback 👍🏻.
> 
> @MaxDesignFR, would you mind sharing what options and CSS you’re using. Or even better, a CodeSandbox with the full setup?
> 
> Best, David

Sure, I made 2 identical CodeSandboxes, the only difference being the flex-basis (33.33% vs 33.34%) :

33.33% version: https://codesandbox.io/s/embla-carousel-default-vanilla-forked-bzit5q?file=/src/css/embla.css:525-542
33.34% version: https://codesandbox.io/s/embla-carousel-default-vanilla-slides-3-slides-33-34-g684o7?file=/src/css/embla.css:525-542

Screen capture from the CodeSandboxes to illustrate my point: https://i.vgy.me/WEvkZF.gif

**Comment by davidjerleke** [comment]
Thank you @MaxDesignFR, very helpful 👍!
Embla is actually behaving as expected here. Here's what the docs say about the [`loop`](http://localhost:8000/api/options/#loop) option:

> Automatically falls back to false if slide content isn't enough to loop. 

What's happening in first example is that Embla makes the decision that the three slide widths combined aren't sufficent for the loop effect to work without any noticeable visual glitches. So it falls back to `loop: false;`.

**You might think:**

_Ok, but I have three slides that cover 100% of the viewport? So it should be able to flip around the fourth slide without any visual glitches?_

**The answer is no:**

Because the slides has to cover `100%` of the viewport plus `1px` to take into account for when the carousel is scrolling (animating). I hope my explanation makes sense. Here's what the upcoming v7 docs say about the `loop` option:

> Enables infinite looping. Automatically falls back to false if slide content isn't enough to loop. Embla will apply `translateX` or `translateY` to the slides that need to change position in order to create the loop effect.

Please let me know if you have any ideas of how to improve the explanation if you think it's insufficient.

Cheers,
David

**Comment by MaxDesignFR** [comment]
> What's happening in first example is that Embla makes the decision that the three slide widths combined aren't sufficent for the loop effect to work without any noticeable visual glitches. So it falls back to loop: false;

@davidjerleke Thank you for further details, I came to this understanding as well. But it's taken me some time to figure this out, on my first project using Embla I got stuck thinking this couldn't loop because I didn't have enough slides outside of viewport, when actually I could just have updated the slides width — let's say 5 x 20.01% instead of 5 x 20% — in order for the loop to work.

So my feedback was to ask if the library could manage to detect and somehow take into consideration this very tiny margin of error. I don't know whether it's easily doable, but it would definitely be more developer-friendly, because I don't think this "issue" is obvious to understand unless messing around with the code for a while (at least I did).

Otherwise, maybe more than sufficient, update the docs to add a simple "how it works" explanation. Such as :

> Enables infinite looping. Automatically falls back to false if slide content isn't enough to loop (total width of the slides must be greater than 100%). Embla will apply translateX or translateY to the slides that need to change position in order to create the loop effect.

Maybe not like that but you get my point. As far as I'm concerned it's not an issue since I understand this cog now, but I believe there is added value for the (new) users to document this behavior.

**Comment by davidjerleke** [comment]
@MaxDesignFR Thank you for your response.

> But it's taken me some time to figure this out, on my first project using Embla I got stuck thinking this couldn't loop because I didn't have enough slides outside of viewport, when actually I could just have updated the slides width

I think you make a good point and we should do something to minimize the risk of confusion or running into this problem. As you already have made clear, there are two ways of tackle this:

1. Do something with the Embla core.
2. Update the docs so it communicates this better.

> So my feedback was to ask if the library could manage to detect and somehow take into consideration this very tiny margin of error. I don't know whether it's easily doable, but it would definitely be more developer-friendly, because I don't think this "issue" is obvious to understand unless messing around with the code for a while (at least I did).

If the library were to do something when this happens it has to detect the problem and probably touch the DOM in a way which it doesn't normally do. v7 only manipulates `transform: translate` on the container and the slides that need to change position in order to create the loop effect. It would also increase bundle size a bit. There are probably other ways of dealing with this so I'm open to suggestions if you have something in mind.

> Maybe not like that but you get my point. As far as I'm concerned it's not an issue since I understand this cog now, but I believe there is added value for the (new) users to document this behavior.

100%. We want to get rid of the confusion. By the way, have you tried setting the widths like this instead:

```ts
.embla__slide {
  flex: 0 0 calc(100% / 3); 
}

// ...or:

.embla__slide {
  flex: 0 0 calc(100% / 3);
  width: calc(100% / 3);
}
```

...does that behave like expected instead of the unpredictable `flex: 0 0 33.333333333333336%`? If yes, maybe the docs should recommend users to prefer the `calc()` approach instead? This would be one way to communicate it:

<img width="482" alt="docs" src="https://user-images.githubusercontent.com/11529148/181094983-1719f62e-fd3b-4012-8678-7979a496a526.png">

Let me know what you think and thank you for your time.

Best,
David

**Comment by MaxDesignFR** [comment]
@davidjerleke Unfortunately I haven't familiarized myself much with Embla code base, so I don't have a clue if there's a clever way to do that in Embla core. But we enjoy Embla cause it's light, so I guess right now, updating the doc is better than nothing (it would allow devs to understand the requirement for loop to work properly, and eventually save time).

> ...does that behave like expected instead of the unpredictable flex: 0 0 33.333333333333336%? If yes, maybe the docs should recommend users to prefer the calc() approach instead? Please note that this only seem to work with v7 that uses px instead of % and not previous versions. This would be one way to communicate it:

The `33.333333333333336` was generated by a template language (liquid). But I think what matters is how it's computed by the browser. In the computed tab of the dev console, it seems to go up to 4 decimals. I tried with `calc(100% / 3)` and flex-basis is computed as `33.3333%` which — multiplied by 3 — is not strictly superior to 100%, and therefore the slider will not work as expected if those things are combined:
• Loop is activated
• There is only one slide that do not fit into the viewport (eg: 3 slides in viewport at 33% + 1 slide outside viewport)
• Total width of the slides in viewport is not strictly superior to 100%

This is what I highlight here: https://codesandbox.io/s/embla-carousel-default-vanilla-3-slides-calc-100-3-forked-y9py9w?file=/src/css/embla.css:525-550

`calc(100% / 3)` does not fix the issue since it does not solve bullet point number 3. But calc(100.01% / 3)` would (computed as 33.3367). So I see 2 approaches with my current understanding:

1/ The doc. states that their must be at least 2 extra slide outside of viewport for the loop to work properly.
2/ If there is only 1 extra slide outside of viewport, the total width of the slides in viewport must be slightly over 100% to loop properly.

I hope it makes sense. It nearly seems like a niche problem, and yet It's safe to say other people may encounter it.

**Comment by davidjerleke** [comment]
@MaxDesignFR thanks.

After the release of stable v7 I will spend some time to see if there's a simple way for Embla to handle this internally. But for now I will add something to the docs. I think this is a good starting point so thank you for this explanation (I might use a modified version of it if that's ok?):

> 1/ The doc. states that their must be at least 2 extra slide outside of viewport for the loop to work properly.
2/ If there is only 1 extra slide outside of viewport, the total width of the slides in viewport must be slightly over 100% to loop properly.

About this:

> calc(100% / 3) does not fix the issue since it does not solve bullet point number 3. But calc(100.01% / 3)` would (computed as 33.3367).

Did you actually try `calc()` with the **`version 7 release candidate`** as I tried to communicate in my [previous comment](https://github.com/davidjerleke/embla-carousel/issues/298#issuecomment-1195891650)? Because this CodeSandbox is using v6.2.0:

> This is what I highlight here: https://codesandbox.io/s/embla-carousel-default-vanilla-3-slides-calc-100-3-forked-y9py9w?file=/src/css/embla.css:525-550

Because from my tests, v7 behaves different than v6.2.0 and lower. This is (as mentioned in my previous comment) because the move from `%` to `px` seems to make the internal calculations more precise since `px` is an absolute unit. Sorry for repeating myself if you did try `calc()` with v7 but I just wanted to make sure you picked that up.

Thank you for your valuable feedback!

Cheers,
David

**Comment by MaxDesignFR** [comment]
> After the release of stable v7 I will spend some time to see if there's a simple way for Embla to handle this internally. But for now I will add something to the docs. I think this is a good starting point so thank you for this explanation (I might use a modified version of it if that's ok?):

Yes sure, happy I could help.

> Did you actually try calc() with the version 7 release candidate as I tried to communicate in my https://github.com/davidjerleke/embla-carousel/issues/298#issuecomment-1195891650?

I tried v7 pre-release on my end and I encountered the same issue unfortunately. Only it seems with v7 sometimes loop works, sometimes not, depending on the current screen size. I just changed this codesandbox to v7 (https://codesandbox.io/s/embla-carousel-default-vanilla-3-slides-calc-100-3-forked-y9py9w?file=/src/css/embla.css:525-550), and I notice that on narrower screen sizes (tablet/mobile), it is still not looping properly, whereas it loops well on larger screen size, so it still seems inconsistent. From what I observe in this codesandbox, the loop seems to fallback to false once the Embla viewport default size gets shrunken down by the screen viewport size, so that may be a starting point for you.

codesandbox gif preview before/after resize: https://i.vgy.me/Tom5Ce.gif

**Comment by davidjerleke** [comment]
Hi again @MaxDesignFR,

It might be an easy fix after all. Would you mind trying this [CodeSandbox](https://codesandbox.io/s/embla-carousel-react-v7-forked-vknm1z) out? If you can't see any visual glitches when the carousel is looping, this might be the solution.

Thanks in advance.

Best,
David

**Comment by MaxDesignFR** [comment]
Hi @davidjerleke,

That sounds about perfect, it did the trick! Really neat that you could fix this so quick before the next release. I'm curious what's the fix you found out to solve this problem? (don't give yourself a headache if there's too much concept to explain, I'm just curious, developer syndrom to know how things gets fixed aha)

**Comment by davidjerleke** [comment]
Hi @MaxDesignFR,

Glad to hear that it worked. I have some testing in other browsers left to do but let's hope that they will behave the same. 

>  I'm curious what's the fix you found out to solve this problem?

I changed the value on [this line](https://github.com/davidjerleke/embla-carousel/blob/master/packages/embla-carousel/src/components/SlideLooper.ts#L85) to `0.1` (which equals `0.1px`). What this line does is that it basically checks if the total width of the slides in viewport (while shifting positions of other slides) equals the size of the viewport - In other words if the carousel will be able to loop without any visual glitches. 

And I thought setting it to 0.1 will be result in a noticeable glitch when looping slides but seems like I was wrong. I never thought it would work. But it seems like the fractional `px` value `0.1px` is enough.

Cheers,
David
