### ISSUE TITLE
Carousel delay problem when load a large number of images

### ISSUE THREAD

**Issue by gsi-yoangainza** [davidjerleke/embla-carousel#319]
### Bug is related to
-Using embla-carousel with a large number of images on IOS (Safari, Chrome, Firefox)

### Embla Carousel version

- v6.2.0

### Describe the bug
Hi there!

I'm not sure if it's a bug or not, but the behavior of transitions between slides when scrollNext() is odd in my application.

I'm using the carousel to load several images of a gallery in a user profile. The loaded images are `<picture>` tags with the `<img>` tags inside. Using react, we created the Picture component with the above structure: a `<picture>` tag that contains the `<img>` tag.

What's happening is that when the carousel loads a large number of pictures, in IOS the transition becomes very slow. We have used lazy loading, to ensure that when we upload the first picture we already have other 30 in queue. When it loads less pictures still happens but less.

Also, we added a zoom library and that make the transition even slower.

This is a video showing the slowness with a bigger component and zoom functionality:
https://user-images.githubusercontent.com/85452393/170327658-2174ee88-0a37-4767-bf22-6d764247488b.mp4

And this is the smaller component without zoom, which is much faster in the transitions, but sometimes it get slower (picture 22, for instance):
https://user-images.githubusercontent.com/85452393/170340541-5de6da83-537b-449e-90fd-8accb9e70e51.mp4

The following image is showing the DOM when we scrolled through 28 pictures already, and that's why I think this shows -2800%, not sure if this it is normal behavior or not. When the lazy loading loads more pictures the number of elements increases.
![image-console](https://user-images.githubusercontent.com/85452393/170340701-e0738afb-1d6e-4ae7-80f4-adecedc281ca.png)

I'm not sure if it is because we are loading the images the wrong way or it's some kind of conflict with IOS operating system. So I would appreciate some advice about it.

Thanks a lot in advance!

**Comment by davidjerleke** [comment]
Hi @gsi-yoangainza,

Thank you for your question. I don’t have access to your full setup, but it shouldn’t get slow. 

> What's happening is that when the carousel loads a large number of pictures, in IOS the transition becomes very slow.

When I created the infinite scroll example on the documentation website, I tested it with hundreds of images and it didn’t stutter at all. It worked smoothly.

> Also, we added a zoom library and that make the transition even slower.

I have no control over how other libraries affect your performance or not. The only thing Embla does is to transform your container, and if loop is enabled it flips slide positions to create the loop effect. It doesn’t touch the DOM in any other way. I don’t think Embla should get the blame for this.

Kindly,
David

**Comment by davidjerleke** [comment]
Hi @gsi-yoangainza,

As I mentioned, over 200 slides with images worked smoothly when I tested it in different browsers (including the OS and browsers you mentioned) .

**I’m going to get straight to the point (without any intention of being rude):**

Without a reduced test case, which is a CodeSandbox that clearly demonstrates the problem (with unnecessary details stripped),  I’m not going to continue guessing what could be wrong with your setup. Because it’s pointless. It could literally be anything causing this.

If you want me to debug this further you’ll have to provide that CodeSandbox. This is clearly stated under the **Bug reports** in the [contribution guidelines](https://github.com/davidjerleke/embla-carousel/blob/master/.github/CONTRIBUTING.md#bug-reports). Please let me know if you intend to provide it or not.
 
Thank you for understanding.

Best,
David
