### ISSUE TITLE
Ability to lock scroll if all slides in view

### ISSUE THREAD

**Issue by Intaria** [davidjerleke/embla-carousel#320]
Hello.

Is it possible to lock scroll or check if all slides shown completely?

I know that we could get container width with containerRect.width inside api "scroll" callback and compare it with the sum of all slides widths, but is there more cleanup way?

**Comment by davidjerleke** [comment]
Hi @Intaria,

I'm not quite sure what you mean by lock scroll. Do you want to disable dragging when all slides have been in view once? Or do you want to be able to determine when the carousel has scrolled to the end of its scrollable length?

Best,
David

**Comment by Intaria** [comment]
Hi @davidjerleke 
Totally disable dragging and overstretching slides when all slides in view at once.

**Comment by vodolazskikh** [comment]
Hi! I have the same question:)

**Comment by davidjerleke** [comment]
@Intaria are you using vanilla JS or React?

**Comment by Intaria** [comment]
@davidjerleke react

**Comment by davidjerleke** [comment]
Hi @Intaria,

If I understand you correctly, you want to disable dragging as soon as the carousel is headed for the end of its scrollable length. Please let me know if this is not the case. Here's a [CodeSandbox](https://codesandbox.io/s/embla-carousel-default-react-forked-qh8cfj) demonstrating that. This is how the sandbox works:

- As soon as the carousel is headed for the end of its scrollable length, either by dragging or clicking the next button, the carousel is re-initialized with the option `draggable: false`.
- Note that the carousel will continue scrolling until it reaches its end destination.

Is this what you wanted to achieve?

Best,
David

**Comment by davidjerleke** [comment]
@Intaria have you had any chance to read [my response](https://github.com/davidjerleke/embla-carousel/issues/320#issuecomment-1190624652)?

**Comment by stepanjakl** [comment]
I'll chip in here. It would be nice to have an option (similar to `draggable` - something like `noScrollWithAllSlidesInView` - probably with more compact wording though) on the initialisation of the carousel. When all slides are in view at once, hence there is no need to use the scroll - then disable it. But this would be an option for the slider, not an extra function with overflow computation etc. That's at least what I would propose.

**Comment by davidjerleke** [comment]
Hi @stepanjakl,

Thank you for your response. You didn't answer if the [solution](https://github.com/davidjerleke/embla-carousel/issues/320#issuecomment-1190624652) I provided here was what you wanted to achieve? 

I have to weigh feature request carefully because one of the biggest selling points of Embla is that it's very lightweight but still offers a lot of functionality. Its API is very extensible - Both using the public API and the possibility to use and create plugins is what makes it very extensible. This is the first time in a couple of years that someone asks about this feature. So I don't want to prioritize building it into the core and burden other users with an increased bundle size, unless it gets a whole lot of traction/attention. In contrast, an example of a feature request that got very much attention was the new [breakpoints option](https://www.embla-carousel.com/api/options/#breakpoints) that was released with v7 yesterday.

So for now I would say that the little function I shared in my solution is what I can offer. I hope this makes sense.

Best,
David

**Comment by stepanjakl** [comment]
I understand. The required outcome can definitely be achieved by using Embla's API. The solution you provided is close to what's needed, except it should disable the scroll on initialization and/or possibly even when slide widths change. For instance, on the desktop you could have 2 slides with 50% width. They fit the container area without overflowing - scroll can be disabled. On the mobile, slide width changes to 100%, therefore one slide would overflow - scroll is enabled. I would say it's not a priority. I could also create a codepen solution for this later.

**Comment by davidjerleke** [comment]
Hello again @stepanjakl,

> For instance, on the desktop you could have 2 slides with 50% width. They fit the container area without overflowing - scroll can be disabled. On the mobile, slide width changes to 100%, therefore one slide would overflow - scroll is enabled.

I think you can do it like this:

```ts
const toggleActiveWhenScrollable = () => {
  const isScrollable = embla.internalEngine().scrollSnaps.length > 1
  emba.reInit({ active: isScrollable })
}

const embla = EmblaCarousel(emblaNode, { loop: false })

embla.on('resize', toggleActiveWhenScrollable)
toggleActiveWhenScrollable()
```

Let me know if it helps.

Best,
David

**Comment by stepanjakl** [comment]
Thank you David, that is a good solution.

**Comment by adonaicandido** [comment]
> Hello again @stepanjakl,
> 
> > For instance, on the desktop you could have 2 slides with 50% width. They fit the container area without overflowing - scroll can be disabled. On the mobile, slide width changes to 100%, therefore one slide would overflow - scroll is enabled.
> 
> I think you can do it like this:
> 
> ```ts
> const toggleActiveWhenScrollable = () => {
>   const isScrollable = embla.internalEngine().scrollSnaps.length > 1
>   embla.reInit({ active: isScrollable })
> }
> 
> const embla = EmblaCarousel(emblaNode, { loop: false })
> 
> embla.on('resize', toggleActiveWhenScrollable)
> toggleActiveWhenScrollable()
> ```
> 
> Let me know if it helps.
> 
> Best, David

Could you provide a example for React please? I'm trying to adapt your example but no success so far.

**Comment by bel7aG** [comment]
is there a way to make embla don't block scroll on vertical slides (axis y) ? 

on mobile when embla is full width scrolling will just keep sliding embla rather then scrolling the body

**Comment by Ingramz** [comment]
Heads up for anyone trying to use the example code posted here. `resize` event won't fire any longer after `active` is set to `false`. 

https://github.com/davidjerleke/embla-carousel/blob/7cc1aee2506e7ec4ffeb4eaadb94b7259b286c1c/packages/embla-carousel/src/components/EmblaCarousel.ts#L110-L117

As a workaround I suggest implementing your own `ResizeObserver` and using that with the event handler.

**Comment by Lshiroc** [comment]
> is there a way to make embla don't block scroll on vertical slides (axis y) ?
> 
> on mobile when embla is full width scrolling will just keep sliding embla rather then scrolling the body

You can achive this via `breakpoints`. If you know when will you show the all slides you can just set the screen size like this:
```js
const [emblaRef] = useEmblaCarousel({
  breakpoints: {
    '(min-width: 1250px)': { active: false }
  }
});
```

**Comment by dbismut** [comment]
> ```ts
> ```ts
> toggleActiveWhenScrollable()
> ```
> 
> 
>     
>       
>     
> 
>       
>     
> 
>     
>   
> ```

Yep I second this, I don't think this issue should be closed.

**Comment by davidjerleke** [comment]
@dbismut what exactly do you want to achieve?

**Comment by dbismut** [comment]
First of all, wonderful job on this package, thanks a lot for it.

I'd like the same thing as the original comment: deactivate the carousel when all slides are fullly visible. Your solution works great to deactivate the slideshow, but as pointed out in [this comment](https://github.com/davidjerleke/embla-carousel/issues/320#issuecomment-2118253329) by @Ingramz the resize stops working once you've deactivated the carousel.

Which means that going from activated to deactivated works, but not the other way around since the resizeHandler doesn't fire when the carousel is not activated.

Does that make sense?

**Comment by davidjerleke** [comment]
@dbismut thanks for clarifying. You can control when the carousel should react to drag events with [`watchDrag`](https://www.embla-carousel.com/api/options/#watchdrag) like so:

```tsx
function isScrollable(emblaApi) {
  return emblaApi.internalEngine().scrollSnaps.length > 1;
}

const emblaApi = EmblaCarousel(emblaNode, {
  watchDrag: (emblaApi) => isScrollable(emblaApi),
  loop: false
})
```

As for navigation buttons like next/prev and dot buttons, they're not built in so you can stop any scrolling when you want like so:

```tsx
function scrollNext() {
  if (isScrollable(emblaApi)) {
    emblaApi.scrollNext()
  }
}
```

...etc.

**Comment by dbismut** [comment]
Oh I see, thanks a lot for this!

**Comment by HarleySalas** [comment]
I'd still like to see this feature be implemented.

I have an instance where all slides are varying widths and there is no way to tell how many scroll slides should be visible at any given breakpoint, to determine if it should be scrollable or not.

An option that simply disables embla entirely if all scroll snaps/slides are in view would be really nice. Not via breakpoints, or any such workarounds. ie; if there is nothing overflowing the carousel viewport, do not allow scrolling. Thats it.

**Comment by davidjerleke** [comment]
Hi @HarleySalas,

Thank you for your input. With no intention of being rude: 

Everyone wants the library to be super convenient with options that solve all their use cases automatically, and they want me to make that happen.

My free time is limited. The hardest part of adding a new feature isn’t the coding—it’s the planning, research and figuring out the best way to implement it without breaking the current code style or quality. That’s the very time consuming part of the process. Coding the feature usually only takes a few hours.

Before I add anything to the core library, there needs to be significant demand for it. If I added every requested feature immediately, the library would become bloated and huge. Many developers like Embla because it’s lightweight and very extensible, so I always have to keep that balance in mind.

While a few developers are interested in this issue, keep in mind that Embla Carousel is used in over 100,000 GitHub repositories—not counting projects using it via CDN or other services like BitBucket etc. Compared to that scale, interest in this feature has been relatively low.

If you support this feature request, the best way to show it is to add a 👍🏻 reaction to the [original post](https://github.com/davidjerleke/embla-carousel/issues/320#issue-1249228365). That’s easier for me to track than reading through multiple comments.

Until there’s enough demand for this feature, you’ll need to stick with [this solution](https://github.com/davidjerleke/embla-carousel/issues/320#issuecomment-2357756786).

Best regards,
David

**Comment by jbach** [comment]
Hi @davidjerleke,
how would you implement your [proposed solution](https://github.com/davidjerleke/embla-carousel/issues/320#issuecomment-2357756786) in v9?

In a carousel with `slidesToScroll: 'auto'` and variable width slides I can use `emblaApi.snapList().length` to determine draggability, but `draggable` does not accept a dynamic function?

Cheers,
Jonas

**Comment by davidjerleke** [comment]
@jbach please check the [cancelling events](https://www.embla-carousel.com/api/events/#cancelling-events) section which demonstrates how to cancel drag events by intercepting the `pointerdown` event. That way, you can control if the carousel should be draggable without changing the `draggable` option.
