### ISSUE TITLE
Stale Plugin options (v7)

### ISSUE THREAD

**Issue by xiel** [davidjerleke/embla-carousel#332]
### Bug is related to

- [x] embla-carousel (core package)
- [x] embla-carousel-react
- [x] all plugins

### Embla Carousel version

- v7.0.0-rc01

### Describe the bug

- Changing the options to a plugin does not trigger a re-init of the plugin with the new options

### CodeSandbox

- https://codesandbox.io/s/embla-carousel-default-react-forked-e7wd1e?file=/src/js/EmblaCarousel.js

### Steps to reproduce

- Change options of a plugin after initialisation
- The plugins keeps working with initial options

### Expected behavior

- New options should destroy & re-init the plugin

### Additional context

- This worked in previous versions
- I noticed this bug when updating the demos for https://github.com/xiel/embla-carousel-wheel-gestures/pull/170

**Comment by davidjerleke** [comment]
Hi @xiel,

Thanks for creating this issue. It was actually intentional because I've never used the feature with auto re-init plugins when plugin options change yet. But now that I think about it twice, it makes sense to keep that convenient feature.

Does this updated [CodeSandbox](https://codesandbox.io/s/embla-carousel-react-v7-4r5fu9) behave as expected?

Cheers,
David

**Comment by xiel** [comment]
@davidjerleke Yes, that works as expected. Thank you!
