### ISSUE TITLE
Carousel sometimes overflows horizontally

### ISSUE THREAD

**Issue by ivan-kleshnin** [davidjerleke/embla-carousel#339]
### Bug is related to

- [x] embla-carousel (core package)
- [x] embla-carousel-react

### Embla Carousel version

- ^7.0.0-rc05

### Describe the bug

**Carousel sometimes overflows horizontally if the number of slides >= 3.**

It's hard to describe with words so I've made a [video description](https://drive.google.com/file/d/1-LXdDHYZlFuHI26DUELfg1JQME2wHAoS/view?usp=sharing).

### GithubRepo

- https://github.com/ivan-kleshnin/embla-carousel-bug (with steps to reproduce)

### Expected behavior

Correct width. I'm not 100% sure that it's really an E.C. bug – sorry if I've missed some CSS rule or a config option.
I swear I spent some time debugging the problem and checking with docs before posting this 🙏

**Comment by davidjerleke** [comment]
Hi @ivan-kleshnin,

Thank you for testing the release candidate. Are you uncommenting testimonials when your dev server is running with hot module replacement? That might be the cause. What happens if you hard refresh the page? 

If you want Embla to listen to when a prop changes like a testimonial prop, please read [this guide](https://www.embla-carousel.com/guides/add-and-remove-slides/#with-react).

Let me know if it helps!

Best,
David

**Comment by ivan-kleshnin** [comment]
@davidjerleke thank you for the response! Yes, it's indeed a CSS issue because it persists when I disable Embla.
Still, it's a bit relevant to the library as the behavior boils down to the following lines (IMO):

```
<Box
  flexShrink="0"
  flexBasis="100%"
  height="100%"
>
  ...
</Box>
```

which are copy-pasted from the docs. 

As screen width passes a certain point, the card refuses to shrink further.

I've tried different combinations of `flexBasis` and `flexShrink` with no sucess so far.

**Comment by davidjerleke** [comment]
Hi @ivan-kleshnin,

So I got more time to look into your problem. 

> Still, it's a bit relevant to the library as the behavior boils down to the following lines (IMO):

I would say not relevant. Because it turns out that this has nothing to do with Embla at all but the problem is rather caused by a faulty grid declaration. I didn't have the permissions to push a branch with the fix to your repository so I'm going to show you how to solve it:

Go to the [following file](https://github.com/ivan-kleshnin/embla-carousel-bug/blob/main/layout/Layout.jsx#L10) in your repository and change the following:

```js
import { Grid } from "@chakra-ui/react";
import Head from "next/head";
import * as React from "react";
import { MainMenu } from "./MainMenu";
import { Footer } from "./Footer";

// Layout
export function Layout({ children }) {
  return (
    <>
      <Grid
        templateRows="auto 1fr auto"
        minHeight="100vh"
        gridAutoColumns="100%" // <-- Add this
      >
        {/*<MainMenu/>*/}
        <div>Menu</div>
        {children}
        {/*<Footer/>*/}
        <div>Footer</div>
      </Grid>
    </>
  );
}
```

Embla carousel is quite different from other carousel libraries because it lets you use any CSS you want. It only reads your slide positions when it initializes. Many carousel libraries out there add all sorts of styles to your slides like `position: absolute;` and so on which can be convenient yes. But they often come with bigger bundle sizes and don't give you full control over your markup like Embla does. This "freedom" Embla gives you with the CSS makes it possible for users to write CSS that causes problems. The Embla docs can't cover all possible combinations of CSS that could lead to problems. It only shows you a minimal setup example and you'll have to get your CSS right from there.

This can be hard to grasp at first for users coming from other carousel libraries to Embla. One thing to note is that when you're having issues with items overflowing or not being positioned correctly, almost 10 out of 10 cases will be because the CSS isn't setup correctly. 

> which are copy-pasted from the docs.

```jsx
<Box
  flexShrink="0"
  flexBasis="100%"
  height="100%"
>
  ...
</Box>
```

This isn't copy pasted from the docs? It should be like [this guide shows](https://www.embla-carousel.com/guides/slide-container/#using-flexbox): 

```jsx
<Box
  flexShrink="0"
  flexGrow="0"
  flexBasis="100%"
  height="100%"
>
  ...
</Box>
```

I hope this helps.

Best,
David

**Comment by ivan-kleshnin** [comment]
Thank you David 🙏  You've basically nailed it so I have littely to add!  
I really appreciate the time you've put into this mini-research and I believe this issue will help other people, not only me.

**Comment by davidjerleke** [comment]
No worries. Good luck and have a nice one 🙂.
