### ISSUE TITLE
Your website is missing https cert when accessed without www

### ISSUE THREAD

**Issue by EarthlingDavey** [davidjerleke/embla-carousel#348]
### Bug is related to

- [ ] embla-carousel (core package)
- [ ] embla-carousel-react
- [ ] embla-carousel-autoplay
- [ ] embla-carousel-auto-height
- [ ] embla-carousel-class-names
- [x] embla-carousel-docs (documentation website)

### Describe the bug

Your website is missing https cert when accessed without www

### Steps to reproduce

1. Go to [this post on reddit](https://www.reddit.com/r/nextjs/comments/n5cztk/comment/gx2b5tc/?utm_source=share&utm_medium=web2x&context=3)
2. Click on the link
3. You'll see the error

### Expected behavior

Silent redirect to the website with www prefix

**Comment by davidjerleke** [comment]
Hi @EarthlingDavey,

Thank you for reporting this.

> Your website is missing https cert when accessed without www

I don't think you can access the documentation website when you browse [https://embla-carousel.com/](https://embla-carousel.com/) because the browser can't establish a secure connection?

I just checked with my domain name provider and in order to create an A record to achieve this, I need to upgrade my plan from `Domain Only` to a more expensive plan: 

- **My current plan:**  38 USD annual fee
- **After upgrading:** 112 USD annual fee

There are some great souls out there donating money to support this project but at the time of writing, the donations so far are just enough to pay the annual fee of my current plan. I'm investing my spare time in this project and I also don't want to start paying more money just to make this redirect. In other words you'll have to accept that you need to get your links right and include **www** in them.

I hope that makes sense.

Best,
David

**Comment by EarthlingDavey** [comment]
Hi @davidjerleke , thanks for getting back to me. First off please don't take this issue as a nag. The intent is to try and help :)

The fees seems really quite expensive, I think maybe there is a mistake. I've only used 4 domain registrars, but all of them allow for multiple A records for free, and I think that is quite usual. For example https://www.hetzner.com/dns-console is free and might fit your DNS needs.

Regardless of this issue, but bcause you mention donations/contributions...
I have just sent about $38 to say thank you. I discovered this package only yesterday, it has been a joy to use and is in production already today ( https://usedandloved.com/items/weddings ).

Cheers ✌️

**Comment by davidjerleke** [comment]
Hi @EarthlingDavey,

Sorry if I came across as rude. I didn't really mean to. And I really appreciate any improvement suggestions for Embla Carousel, be it the core package or the documentation website. So I definitely appreciate your suggestion 🙂.

> I've only used 4 domain registrars, but all of them allow for multiple A records for free, and I think that is quite usual.

My provider allows free A records, but the problem is that I need to upgrade my plan in order to get a SSL certificate. For example, I have an A record pointing `http://embla-carousel.com` --> `https://www.embla-carousel.com`. But I probably need an SSL certificate to point `https://embla-carousel.com` --> `https://www.embla-carousel.com`. I want to mention that domain names and similar aren't my area of expertise so please correct me if I'm wrong 🙂. I'm using GitHub pages by the way so that's why the website has an SSL certificate today.

> Regardless of this issue, but because you mention donations/contributions...
I have just sent about $38 to say thank you. I discovered this package only yesterday, it has been a joy to use and is in production already today ( https://usedandloved.com/items/weddings ).

Wow! Thank you so much @EarthlingDavey ❤️. That's another paid year for the domain name. That's very generous of you! And thanks for sharing the link. It's really great to see Embla in production - It really boost my motivation.

Cheers!
David

**Comment by EarthlingDavey** [comment]
hey, you weren't rude - I just didn't want you to feel like I was demanding a fix 😅

Ah, I understand, yes to need to have 2 ssl cretificates to do the redirect `https://embla-carousel.com --> https://www.embla-carousel.com`. I think sometimes a single certificate will cover the root domain and a sub domain, like `embla-carousel.com` and `www`.

Any way, I'm glad I could be a boost... and it's good to know I have a part in keeping your site going for a while.

See you round ... ( maybe with a PR or discussion ;) ).
