### ISSUE TITLE
Navigation bug

### ISSUE THREAD

**Issue by 7iomka** [davidjerleke/embla-carousel#376]
### Bug is related to

- [x] embla-carousel-react

### Embla Carousel version

- latest

### Describe the bug

About 2 weeks ago I found an [issue](https://github.com/mantinedev/mantine/issues/2447#issuecomment-1257450708) with Mantine wrapper for embla-carousel
The issue was that the formula that was supposed to take into account the gap between the slides did not work as expected. Because of what I thought that the navigation is not working as expected.
Today I writing the code that partially fixes the problem with the calculation formula, but the navigation still works incorrectly

- A clear and concise description of what the bug is.

### CodeSandbox

- [The link to a CodeSandbox that demonstrates the bug clearly. ](https://codesandbox.io/p/github/7iomka/effector-react-form-flow/draft/suspicious-austin?file=%2Fsrc%2Fwidgets%2Fproduct%2Fproduct-carousel%2Fproduct-carouse.styles.ts&selection=%5B%7B%22endColumn%22%3A61%2C%22endLineNumber%22%3A75%2C%22startColumn%22%3A61%2C%22startLineNumber%22%3A75%7D%5D)

### Steps to reproduce

1. Open demo
2. Try to navigate with arrow buttons
3. 1nd, 2nd click - nothing happens, after 3rd click - it runs, and etc.

### Expected behavior

- Navigation works as normally

**Comment by davidjerleke** [comment]
Hi @7iomka,

Thank you for your bug report. If you’re experiencing problems with the Embla Mantine wrapper, you should create an issue on the Mantine repository and not here. I don’t provide Mantine support too.

If you can reproduce the problem with the raw Embla API, that is without the Mantine wrapper, then the place to create a bug report is here.

Let me know how it goes.

Best,
David

**Comment by 7iomka** [comment]
@davidjerleke 
I tried to reproduce, so there is something similar behavior I think:
https://codesandbox.io/s/embla-carousel-arrows-dots-react-forked-4w43qt?file=/src/js/EmblaCarousel.js

**Comment by 7iomka** [comment]
Also I would like to ask a question - why is the initial indent on the left side set?
<img width="845" alt="image" src="https://user-images.githubusercontent.com/18473137/192330476-f443c49b-58eb-4278-912e-d4cf01c1c3a9.png">
I think this is related with approach which I used to include gap in slide width
But it is a very common approach
https://codepen.io/7iomka/pen/abGBQmd

**Comment by davidjerleke** [comment]
Thanks for the CodeSandbox @7iomka,

Embla just reads slide dimensions and the distance between slides when initialised, it doesn't modify any margins or slide widths. You shouldn't have negative margin on the container. Just set margins on the slides and it will work:

```diff
.embla__container {
  display: flex;
  user-select: none;
  -webkit-touch-callout: none;
  -khtml-user-select: none;
  -webkit-tap-highlight-color: transparent;
- margin-left: calc(-1 * var(--slide-gap) / 2);
- margin-right: calc(-1 * var(--slide-gap) / 2);
}
```

As an alternative approach you can use the negative container margin left, and positive slide padding left trick:

```diff
.embla__container {
  display: flex;
+ margin-left: calc(-1 * var(--slide-gap));
}

.embla__slide {
  position: relative;
+ flex: 0 0 var(--slide-size);
+ padding-left: var(--slide-gap);
}
```

Which is why this works:

> Note: when you use padding approach, this negative indent will not appear

This is purely CSS related and has nothing to do with Embla.

Best,
David

**Comment by 7iomka** [comment]
@davidjerleke 
First approach from proposed give me initial negative offset
https://codesandbox.io/s/embla-carousel-arrows-dots-react-forked-ebgo4b?file=/src/css/embla.css
Second (alternative) approach is the only working approach in terms of a correct initial offsets and fit.
https://codesandbox.io/s/embla-carousel-arrows-dots-react-forked-6kzu72?file=/src/css/embla.css

Thanks for explanations.
So, this was my second question of this issue, what about first and main question? Why navigation woking so weird? 
I have total items count - 7. Slide width is 20%, it means that on view is 5 slides. slidesToScroll is by dafault 1.
So, when I click next button, I expect to have slide to 1 right, than after second click next button needed to be disabled.
What's wrong with my configuration?

**Comment by davidjerleke** [comment]
@7iomka,

The first approach also works if you **remove the negative margin** on the `.embla__container` class and make sure to **only set margins on the slides**.

Best,
David

**Comment by davidjerleke** [comment]
Hi @7iomka,

⚠️ Please note that the margin feature was released with Embla v6 and up. Your CodeSandbox is using v5 which is an old version. I recommend you to use the latest version.

This is why you can’t get the margins to work. Here’s a working CodeSandbox:

[https://codesandbox.io/s/embla-carousel-arrows-dots-react-forked-wd5b9y](https://codesandbox.io/s/embla-carousel-arrows-dots-react-forked-wd5b9y)

Best,
David

**Comment by 7iomka** [comment]
@davidjerleke , yes, it works, but it also produce unexpected spaces
<img width="694" alt="Снимок экрана 2022-09-27 в 07 45 06" src="https://user-images.githubusercontent.com/18473137/192434279-a5596726-b1b9-4185-8d73-deeb7c4ac527.png">

It could be compensated by negative margin values on the container, but since you say they are not allowed on the container, the only viable approach at the moment is the alternative one with padding, proposed above

**Comment by davidjerleke** [comment]
Hi again @7iomka,

No it's actually working as expected. As I said [here](https://github.com/davidjerleke/embla-carousel/issues/376#issuecomment-1258366383):

> Embla just reads slide dimensions and the distance between slides when initialised, it doesn't modify any margins or slide widths.

This is described [here in the docs](https://www.embla-carousel.com/guides/slide-container/).

So Embla leaves your container exactly as you set it up with CSS. What happens to a container where the first child has `margin-left` and the last child has `margin-right`, without the Embla script being involved? You get these spacings you're describing as "unexpected" of course. It seems like many devs have a hard time understanding that Embla gives you nearly total freedom when setting up your HTML and CSS, in contrast to many other carousel libs that add all sorts of styling on your elements. There are benefits with the Embla approach:

- Devs can use any markup they like.
- The bundle size is much smaller.

One downside with this approach is that:

- Devs have to get their CSS right.

Now sorry for not being clear. In your example, the first slide has `margin-left` and last slide has `margin-right`. That's why you're seeing these gaps. 

> And by the way, it would be nice to update the examples from the documentation for the latest versions of the plugin if they include any critical updates.

There's an issue that will sync the example CodeSandboxes with the latest documentation examples but I haven't had the time to do much there yet:

- #281

It's easy for devs to just come here and say that it should be like this or that. I'm the sole developer and I simply don't have enough time to maintain the core library, all the wrappers, almost all the plugins, the documentation and the examples. It's an incredible amount of work with no salary. So if you want everything to be up to date you can make either make contributions or consider funding this project.

Kindly,
David
