### ISSUE TITLE
Endless Scrolling

### ISSUE THREAD

**Issue by 0xIanB** [davidjerleke/embla-carousel#384]
During Production the Embla Carousel Stops at the end of scroll, but once deployed it continues forever without stopping. Am I missing something?

![image](https://user-images.githubusercontent.com/101611997/195717835-6cdafa00-f87c-44bd-8819-70d4144fe499.png)
![image](https://user-images.githubusercontent.com/101611997/195717886-6f049c00-bb7b-4dc1-b53b-4ea918f88f7d.png)
![code](https://user-images.githubusercontent.com/101611997/195718168-fc36185e-8706-4239-ab37-a76b6614995d.png)

**Comment by davidjerleke** [comment]
Hi @ianboyle,

Thanks for your question. Embla doesn’t do anything different based on the environment (dev or prod), so it’s most likely not a bug with Embla. It’s likely either expected behavior (but you may have missed that part in the documentation explaining this), or related to something with a faulty setup.

It’s not clear to me what you mean by endless scrolling? Care to share a screen recording?

Best,
David

**Comment by ianboyle** [comment]
@davidjerleke 

Thanks for responding! Sorry I did not mean to infer a bug with Embla itself, I am just at a loss for what is happening, although I highly suspect I am missing something or using incorrect syntax. Basically I want it to end scrolling after the last Slide div. In production it stop. But in the zipped screen recording you will see in deployment I can scroll forever. 

I appreciate any input. Sorry for the disturbance.

[Shredding Sassy - Brave 2022-10-14 13-44-34.zip](https://github.com/davidjerleke/embla-carousel/files/9788894/Shredding.Sassy.-.Brave.2022-10-14.13-44-34.zip)



![CarouselHolder](https://user-images.githubusercontent.com/101611997/195910861-42145f17-317c-4059-b38f-fd6d7f06c233.png)
![EmblaCarousel](https://user-images.githubusercontent.com/101611997/195910869-55349888-5f06-4dca-bf73-53a348e4361a.png)

**Comment by taskrider2022** [comment]
I have the same Problem.

If I run the Slider on the locale development environment all is fine and it will be stop at the last visible item. 
If build the app I can scroll and the slider won't stop at the last item. 

It's the same construction like the author.

**Comment by davidjerleke** [comment]
@ianboyle or @taskrider2022 could any of you share a link where the problem is present?

Because it’s impossible for me to debug if I don’t know how your setup looks like, or if you can’t share any substantial information except a screenshot with fragments of your code.

Thanks in advance,
David

**Comment by davidjerleke** [comment]
@taskrider2022 what happens if you resize the browser in production? Is the endless scrolling still happening after a resize?

**Comment by taskrider2022** [comment]
Yes the problem still exists

**Comment by ianboyle** [comment]
I am just out right now, but once I arrive back to my PC I can link my live site and repo here.

**Comment by ianboyle** [comment]
@davidjerleke 

Live Site | https://sassy-prod.vercel.app/

Repo | https://github.com/ianboyle/sassy-prod

**Comment by ianboyle** [comment]
@davidjerleke no problem! Sorry for delay, been busy with kids lol. I sincerely appreciate your help.

**Comment by ianboyle** [comment]
I tried to disable both of those with no success, it's an odd thing because when I run it in a dev environment it snaps back as it's designed to do. It only has this endless scroll when I deploy it. So when I run under local host it snaps back.

**Comment by davidjerleke** [comment]
@ianboyle did you try disabling them in dev mode or prod? I think you need to try the latter if you didn’t do that.

> it's an odd thing because when I run it in a dev environment it snaps back as it's designed to do. It only has this endless scroll when I deploy it. So when I run under local host it snaps back.

Of course it’s possible that this is a bug with Embla but Embla doesn’t do anything different in its code based on the environment (dev/prod), so I would definitely start looking elsewhere.

My guess is that some library you’re using is doing something different in prod and dev mode, which is affecting element dimensions. If this is the case, Embla can’t pick up the correct dimensions of the container and/or the slides. So I would try removing stuff and building the production bundle and see if it starts working. I would literally try removing anything from animation libraries to next features like next image to find the culprit.

Because @taskrider2022 has the same problem it could be wise to see if you’re using the same libraries and if so what libraries. Maybe that could help us figure out what’s causing this.

**Comment by davidjerleke** [comment]
@ianboyle is the repository you linked to restricted? Or can I download it locally?

**Comment by dsaket** [comment]
I am facing the exact same issue described here on latest v7.0.3.

**Comment by davidjerleke** [comment]
@ianboyle @dsaket @taskrider2022 just to be clear: The contribution guidelines clearly state that any [bug report](https://github.com/davidjerleke/embla-carousel/blob/master/.github/CONTRIBUTING.md#bug-reports) should have a **CodeSandbox with a reduced test case**.

**Comment by dsaket** [comment]
@davidjerleke I tried with v6.2.0 and the issue went away. Thanks for the suggestion!! And yes I am using NextJS.

**Comment by davidjerleke** [comment]
@dsaket I still think there is some funky business going on with NextJS or another library causing Embla to not be able to read the correct dimensions. Downgrading isn’t an actual “solution“ but the reason it works is because Embla v6 uses percentage for transitions and v7 uses pixels.

**Comment by ianwboyle** [comment]
I reverted to v6.2.0 and it works as expected the same in dev as prod. 

I am going to give this a try with React only and not Next JS to see if it has something to do with the Image link or a dependency.

**Comment by dsaket** [comment]
@davidjerleke that's the interesting thing...the issue only comes with the prod build and not with the dev build of NextJS.

**Comment by davidjerleke** [comment]
@dsaket @taskrider2022 @ianboyle have you tried different versions of NextJS?

**Comment by davidjerleke** [comment]
@dsaket @taskrider2022, I'm able to reproduce the problem locally in `prod` mode. So here's a weird thing:

- When I include the Embla script locally in the project (not as a Npm package) it works in `prod` too. 

Would you mind trying that and see if the problem goes away?

**Comment by davidjerleke** [comment]
Hi all (@0xIanB, @dsaket, @taskrider2022),

I just released [v7.0.4](https://github.com/davidjerleke/embla-carousel/releases/tag/v7.0.4). Bump your Embla package to the latest and give that a go. Let me know if the endless scrolling problem goes away in the NextJS prod bundle.

Best,
David

**Comment by dsaket** [comment]
@davidjerleke yes it works as expected now....thanks for the quick patch and a big thanks for the amazing library!!!

**Comment by davidjerleke** [comment]
Thanks for confirming that the patch works @dsaket!

To be fair, I still don’t think this was an actual problem with Embla. I literally didn’t change one line of actual code to fix this, I just pointed the `main` property in the `package.json` to the `UMD` file instead of `CJS` (commonJS). And the bug only happened in the NextJS prod bundle and I wasn’t able to reproduce it in any other context. It was as if the NextJS compiler altered the Embla code in some weird way. 

Anyway, enjoy.

Best,
David

**Comment by davidjerleke** [comment]
Solved in [v7.0.4](https://github.com/davidjerleke/embla-carousel/releases/tag/v7.0.4).
