### ISSUE TITLE
Autoplay other direction (rtl instead of ltr)

### ISSUE THREAD

**Issue by mkruip05** [davidjerleke/embla-carousel#495]
### Feature request is related to

- [ ] embla-carousel (core package)
- [ ] embla-carousel-react
- [ ] embla-carousel-vue
- [ ] embla-carousel-svelte
- [x] embla-carousel-autoplay
- [ ] embla-carousel-auto-height
- [ ] embla-carousel-class-names
- [ ] embla-carousel-docs (documentation website)

### Is your feature request related to an issue?
In the documentation it is possible to set the direction of a slider to a different setting (ltr or rtl), but it seems not working if you use the autoslide plugin.

### Describe the solution you'd like
An extra option for the autoplay plugin to set the direction the other way (rtl instead of ltr)

**Comment by davidjerleke** [comment]
Hi @mkruip05,

I just tested the autoplay plugin with `rtl` and it's working just fine. Just follow these steps:

1. Fork the [Autoplay CodeSandbox](http://localhost:8000/examples/predefined/#autoplay).
2. Follow [these instructions](https://www.embla-carousel.com/api/options/#direction) in the docs.

That's enough to get it working.

Best,
David

**Comment by davidjerleke** [comment]
Please read the [contribution guidelines](https://github.com/davidjerleke/embla-carousel/blob/master/.github/CONTRIBUTING.md#bug-reports). It seems like you've missed quite a lot about how to write your report in order to get proper help. From the guidelines:

> `Do not:` Provide a link to a production site. That's not a test case.

**Comment by mkruip05** [comment]
@davidjerleke sadly doesn't work. I will try to find another workaround. Thanks for your help.

**Comment by davidjerleke** [comment]
Ok so that’s where the confusion comes from. You wrote `ltr` and `rtl`. These abbreviations are almost always used to specify the content direction in web development.

What you want is to be able to set the autoplay to move in the opposite direction. It should advance to the previous snap instead of next.

This is not possible with the current state of things.

I guess you missed this:

- #321

Please read that. Thank you for understanding.

Best,
David
