### ISSUE TITLE
Logos Slider

### ISSUE THREAD

**Issue by Amer-Moh** [davidjerleke/embla-carousel#559]
Hello, I'm trying to create a logos slider using js vanilla, but somehow I get something wrong and the slides are shifted to left, first and last slides are showing half, I tried to fix that using css but I couldn't.
Is there any custom options for this kind of sliders ( Logos Slider / 4 items slider )?

--js---
var emblaNode = document.querySelector('.embla')
var options = { loop: true }
var plugins = [EmblaCarouselAutoplay()] // Plugins

var embla = EmblaCarousel(emblaNode, options, plugins)
---js--

--css--
.embla {
    overflow: hidden;
    margin-bottom: 3.6rem;
  }
  .embla__container {    
    display: flex;
    justify-content:flex-start;
    gap:10px;
    
  }
  .embla__slide {
    flex: 0 0 25%;
    min-width: 0;         
    text-align: center;   
  }

  @media(max-width:768px){
    .embla{
        margin-top: 3.6rem;
    }
    .embla__slide {
        flex: 0 0 100%;
      }    
  }

  .embla__slide img{
    max-height: 70px;
  }
--css--
![image](https://github.com/davidjerleke/embla-carousel/assets/69674040/048db556-b1e6-4547-bb64-8f01a3ab46ab)

**Comment by davidjerleke** [comment]
Hi @Amer-Moh,

In your `embla__container` CSS, remove `justify-content`:

```diff
.embla__container {
  display: flex;
- justify-content:flex-start;
  gap: 10px;
}
```

...so it is this instead:

```css
.embla__container {
  display: flex;
  gap: 10px;
}
```

Always use the [`align option`](https://www.embla-carousel.com/api/options/#align) instead of trying to align with flex-box when using Embla. Other than that, I can't help you much more because you'll have to create a CodeSandbox that demonstrates the problem so I can if you're doing anything else wrong.

Best,
David

**Comment by Amer-Moh** [comment]
Thank you for your reply, align: 'start' works for me :)

**Comment by davidjerleke** [comment]
@Amer-Moh so did I understand you correctly that your problem has been solved?
