### ISSUE TITLE
Carousel transition animation broken on Firefox (117)

### ISSUE THREAD

**Issue by hamidrezahanafi** [davidjerleke/embla-carousel#568]
### Bug is related to

- [x] embla-carousel (core package)

### Embla Carousel version

- v8.0.0.rc12

### Describe the bug
Carousel transition animation broken on Firefox (117)
Better describe it in a video

https://github.com/davidjerleke/embla-carousel/assets/91487491/850667d1-d0b9-46a0-8936-c996a896a7d4

### CodeSandbox

https://codesandbox.io/s/y6vw87

### Steps to reproduce

1. Go to ['Code sandbox](https://codesandbox.io/s/y6vw87) on firefox (latest version 117)
2. Click on Next/Previous and first few transition animations are broken

### Expected behavior
Smooth animations

**Comment by davidjerleke** [comment]
Hi @hamidrezahanafi,

Thank you for your bug report. I just tested this on Firefox 117.0.1 (64-bit), Mac (OSX) and couldn't reproduce this. What device and OS are you using?

Best,
David

**Comment by hamidrezahanafi** [comment]
Hey @davidjerleke I use a 16inch m1pro Mac.
I can reproduce it on my external monitor and if I reduce the Firefox window size on Mac 
Check the video

https://github.com/davidjerleke/embla-carousel/assets/91487491/41728174-0905-48b9-8add-44ea275a11e1

**Comment by davidjerleke** [comment]
Thanks @hamidrezahanafi 👍, I can reproduce it now. I'll investigate it when possible.

**Comment by davidjerleke** [comment]
Hi @hamidrezahanafi,

I've investigated this now and it seems like this was caused by the same problem as you discovered here:

- #571

Looping slides (translating them to achieve the effect) was triggering a resize which in turn was causing Embla to run `reInit()` and hard resetting the carousel - hence the instant transition. I just released [v8.0.0-rc14](https://github.com/davidjerleke/embla-carousel/releases/tag/v8.0.0-rc14) and can't reproduce this problem now. Please try the latest version and see if this problem is solved.

Best,
David

**Comment by hamidrezahanafi** [comment]
Yes tested and it's fixed on FF now. Thanks

**Comment by davidjerleke** [comment]
@hamidrezahanafi **thank you** for finding the bug and explaining it well 🎉!

- Solved in #571.
