### ISSUE TITLE
Another css units in embla__container translate3d() animation

### ISSUE THREAD

**Issue by jakubreron** [davidjerleke/embla-carousel#60]
Hello, is it possible to have an option of selecting another css unit for the transform animation?
I mean: .embla__container is using translate3d(%, 0, 0) for the animations, but from what i've tested on my website, the performance would be better if i used translate3d(px, 0, 0) instead of % value.

Would you consider adding this feature to the Embla Carousel?

Thank you.

**Comment by davidcetinkaya** [comment]
Hi Jakub (@jakubreron),
Thank you for your question.

In the early stages when Embla was an embryo, it actually supported both `percent` and `px` units with an option called unit. But along the way I decided to drop the support for `px` because I didn’t see any advantage supporting it.

I don’t experience any performance issues so I’d appreciate if you could:

- Setup a CodeSandbox demonstrating the issue?
- Tell me which browser (including version) and device that you’re using?

Thank you in advance.

Kindly
David

**Comment by jakubreron** [comment]
Hello, thanks for the reply

My current setup:
OS: Ubuntu 20.04 (there is a better performance on windows, probably due to better hardware acceleration)
Browser: Firefox 75 (chrome is rendering the animations perfectly)

It's hard to provide a code sandbox because as you said the issues are might be due to my setup and because of the other scripts & styles, there is still much to improve on this [website](https://massivepixel.io/) yet

I am experiencing something like in this [issue](https://stackoverflow.com/questions/50409008/css-transform-transition-using-%C2%B4px%C2%B4-more-smooth-performant-than-percentage) - but in a smaller scale and only on Firefox.

It's not really an issue on every non-potato device, but i am trying to improve the performance as much as i can, so i was wondering how it would work if i changed everything to px or rem instead of using the %.

**Comment by davidcetinkaya** [comment]
Thanks for the additional information Jakub (@jakubreron) 👍.

BrowserStack doesn't provide testing for Ubuntu so I can't really test what you're experiencing (nice looking website by the way 🙂). So I'm just gonna throw out a couple of untested thoughts here.

- What happens if you stop the logo carousel? Does that improve performance? Because a continuous animation on a larger space could have a negative impact on browser performance.
- Also, I've noticed that quite many elements have transitions in different ways, which may be heavy on the browser together. Like for example `.testimonials__embla` have a height transition, is that needed? You can try removing some of these and see if it has any effect.
- Are you using hardware-acceleration hacks like `will-change` or `transform: translateZ(0)` on many elements? This can improve performance if used sparingly, but not extensively. [This article](https://css-tricks.com/almanac/properties/w/will-change) may explain it better than me.

There's probably a lot more you could try but these things were the things that came to my mind initially.  

Kindly,
David

**Comment by jakubreron** [comment]
You're right, the logo carousel is making a difference when i disable it, the height can also be pretty expensive, i definitely need to read more about the ```will-change```, ```transform: translateZ()``` and overall css performance tips so i can focus on other things rather than on the carousel itself :smile: 

Sorry for a stupid issue :sweat_smile: 
As always, thank you very much!

**Comment by davidcetinkaya** [comment]
Hello again Jakub (@jakubreron),

I’m happy to hear that it helps 🙂.
There’s obviously much more to browser performance than the things I mentioned but maybe it’s a good starting point?

Don’t apologize, I think it’s always better to ask 👍🏻.

**Comment by davidcetinkaya** [comment]
The `translate3d()` unit will change to `px` instead of `%` in v7:

- #298

**Comment by davidjerleke** [comment]
Released with [v7](https://github.com/davidjerleke/embla-carousel/releases/edit/v7.0.0).
