### ISSUE TITLE
Support pinch-zoom

### ISSUE THREAD

**Issue by kj** [davidjerleke/embla-carousel#645]
### Feature request is related to

- [x] embla-carousel (core package)
- [ ] embla-carousel-react
- [ ] embla-carousel-vue
- [ ] embla-carousel-svelte
- [ ] embla-carousel-autoplay
- [ ] embla-carousel-auto-height
- [ ] embla-carousel-class-names
- [x] embla-carousel-docs (documentation)
- [x] embla-carousel-docs (generator)

### Is your feature request related to an issue?

Pinch zoom isn't working for me on Android (at least in the examples on the website). I noticed in another issue https://github.com/davidjerleke/embla-carousel/issues/480#issuecomment-1567677811 someone commented that it is working under iOS, so this might only affect Android, although I can't be sure.

### Describe the solution you'd like

I'd like to be able to use pinch zoom to zoom in to image details in a slider. I [made a PR](https://github.com/rcbyr/keen-slider/pull/312) for Keen-Slider to get this working, although there's not much development activity over there so the PR hasn't gone anywhere.

The PR just checks whether there are two or more fingers touching the surface before dragging, and adds `pinch-zoom` to `touch-action`.

**Comment by davidjerleke** [comment]
@kj I don’t know anything about Keen-Slider but you can add a callback to the Embla [watchDrag](https://www.embla-carousel.com/api/options/#watchdrag) option to customize the behavior and intercept the drag behavior. In your case, you need to do the following:

1. The second callback argument is the raw event so check if it’s a touch event. Return true if it’s **not** a touch event to allow Embla to continue with its default behavior.
2. Return false if touches has two fingers (it’s a pinch zoom) and otherwise return true to allow Embla to continue with its default behavior.

Best,
David

**Comment by kj** [comment]
Sorry @davidjerleke I didn't forget about this, I've just been a bit distracted. I tried with a minimal setup, basically this:

```
<script defer type="module">
  import EmblaCarousel from './embla-carousel.esm.js';

  EmblaCarousel(document.querySelector('.embla'));
</script>
```

And pinch zoom does work in Firefox for Android with `touch-action: pan-y pinch-zoom`, or when `touch-action` is unset. Only with `touch-action: pan-y;` does it not work. So I'm not sure why it wasn't working for the website examples when I added `pinch-zoom`, but maybe I missed something else. Either way, it's clearly working fine in the typical case without any workarounds (like the touch count I had to add with Keen-Slider), so I'll close this.

It's great to finally have a lightweight carousel that just does these things right!
