### ISSUE TITLE
Scroll snap and slides to scroll calculations are too sensitive

### ISSUE THREAD

**Issue by mozart77** [davidjerleke/embla-carousel#649]
### Bug is related to

- [x] embla-carousel (core package)

### Embla Carousel version

- `v8.0.0rc15`

### Describe the bug

Function scrollSnapList() returns wrong number of elements. 

### CodeSandbox

[- The link to a CodeSandbox that demonstrates the bug clearly.](https://codesandbox.io/p/sandbox/embla-carousel-generator-vanilla-forked-x7p3df)

### Steps to reproduce

1. Take example with dots from Generator
2. Remove one slide
3. Add breakpoints in CSS to change number of slides displayed
4. Watch the number of pages when all slides are visible. There will be 2 pages

### Expected behavior

One page or none when all slides are visible

### Additional context

Video:
https://github.com/davidjerleke/embla-carousel/assets/6299334/8bfdba46-2969-4411-9751-50c8b9477eaf

**Comment by mozart77** [comment]
Another example if we remove max-width from container (watch the dots!)

https://github.com/davidjerleke/embla-carousel/assets/6299334/fba9ffec-2852-45cc-b6b6-340fb3d1deb9

**Comment by davidjerleke** [comment]
Hi @mozart77,

Thank you for your bug report. Yes I’ve actually noted this issues. They are caused by the transition from reading element.getBounding ClientRect to offset dimensions (e. g. offsetWidth, offsetLeft):

- #637

I basically missed to refactor the rounding safeties used in the code. Because client rects give you floating points which is why it was needed before while offset dimensions return whole integers so this is probably causing problems now. I will look into this when possible. Thanks for creating a bug so devs can track this issue.

Best,
David

**Comment by davidjerleke** [comment]
Hi @mozart77,

Would you mind testing the following [CodeSandbox](https://codesandbox.io/p/sandbox/embla-carousel-generator-vanilla-forked-szqmzw?file=%2Fsrc%2Fjs%2Findex.js%3A6%2C1) and see if it behaves as expected now?

Best,
David

**Comment by davidjerleke** [comment]
@mozart77 a bug fix for this was just released in [`v8.0.0-rc16`](https://github.com/davidjerleke/embla-carousel/releases/tag/v8.0.0-rc16).
