### ISSUE TITLE
[Bug]: embla-carousel-autoplay - stopOnMouseEnter NOT WORKING on mouse enter, but only when you click inside the wrapper.

### ISSUE THREAD

**Issue by shaaandi** [davidjerleke/embla-carousel#724]
### Version

8.0.0-rc21

### CodeSandbox

https://codesandbox.io/p/sandbox/embla-carousel-autoplay-react-forked-fsj2d2?file=%2Fsrc%2Fjs%2FEmblaCarousel.jsx%3A2%2C31-2%2C51

### What browsers are you seeing the problem on?

Chrome

### Steps to reproduce

the feature is simply not working for the autoplay plugin

### Expected Behavior

It should work as the naming said.

### Additional Context

it is working in the 7.1.0 version

### Which variants of Embla Carousel are you using?

- [X] embla-carousel **(Core)**
- [X] embla-carousel-react
- [ ] embla-carousel-vue
- [ ] embla-carousel-svelte
- [X] embla-carousel-autoplay
- [ ] embla-carousel-solid
- [ ] embla-carousel-auto-height
- [ ] embla-carousel-class-names
- [ ] embla-carousel-docs **(Documentation)**
- [ ] embla-carousel-docs **(Generator)**

### Before submitting

- [X] I've made research efforts and searched the documentation
- [X] I've searched for existing issues
- [X] I agree to follow this project's Contributing Guidelines for bug reports

**Comment by davidjerleke** [comment]
@shaaandi I can't access your sandbox:

<img width="851" alt="sandbox" src="https://github.com/davidjerleke/embla-carousel/assets/11529148/5022edd3-1eb4-4356-9a96-b61f88e8276b">

**Comment by shaaandi** [comment]
@davidjerleke  mb. https://codesandbox.io/p/sandbox/embla-carousel-autoplay-react-forked-fsj2d2

**Comment by davidjerleke** [comment]
Thanks @shaaandi. 

If I'm to guess, you're trying to achieve some sort of **continuous scroll** with the [`Autoplay`](https://www.embla-carousel.com/plugins/autoplay/) plugin. Is that correct? Please don't do that.

- [Here](https://codesandbox.io/p/sandbox/embla-carousel-autoplay-react-forked-fsj2d2?file=%2Fsrc%2Fjs%2FEmblaCarousel.jsx%3A8%2C3-8%2C60), it doesn't make sense to set duration to `2000`. The docs has a [clear note](https://www.embla-carousel.com/api/options/#duration) about what values are recommended, which is any value between `20 - 60`.
- [And here](https://codesandbox.io/p/sandbox/embla-carousel-autoplay-react-forked-fsj2d2?file=%2Fsrc%2Fjs%2FEmblaCarousel.jsx%3A11%2C1-11%2C16), `delay: 1` doesn't make sense at all for a timer based Autoplay plugin. It's called a timer because it's supposed to run in intervals, not once every millisecond.
- When using values that makes sense, `stopOnMouseEnter` is working just as expected.

If you want to achieve a continuous auto scroll effect, I think you're looking for the [`Auto Scroll`](https://www.embla-carousel.com/plugins/auto-scroll/) plugin which is available in `v8.0.0-rc22`.

Best,
David

**Comment by shaaandi** [comment]
@davidjerleke 

Thanks for the fast response. I am going to use the auto scroll then. Thanks.
