### ISSUE TITLE
[Bug]:  no specific name for plugin import, have to use "index" instead

### ISSUE THREAD

**Issue by NicoPom** [davidjerleke/embla-carousel#798]
### Which variants of Embla Carousel are you using?

- [ ] embla-carousel **(Core)**
- [ ] embla-carousel-react
- [ ] embla-carousel-vue
- [ ] embla-carousel-svelte
- [ ] embla-carousel-autoplay
- [ ] embla-carousel-auto-scroll
- [ ] embla-carousel-solid
- [ ] embla-carousel-auto-height
- [X] embla-carousel-class-names
- [ ] embla-carousel-docs **(Documentation)**
- [ ] embla-carousel-docs **(Generator)**

### Steps to reproduce

I might be wrong, but I can't find the plugin name when trying to import it. Instead I import the index file ti make it work.

### Expected Behavior

Should be specific name like the Wheel Gesture Plugin

### Additional Context

I have also tried...

### Before submitting

- [X] I've made research efforts and searched the documentation
- [X] I've searched for existing issues
- [X] I agree to follow this project's Contributing Guidelines for bug reports

**Comment by sarussss** [comment]
Hi @NicoPom, Is it what you are talking about? https://www.embla-carousel.com/plugins/wheel-gestures/

**Comment by davidjerleke** [comment]
@NicoPom thank you for your bug report.

Please provide a CodeSandbox with your setup that clearly demonstrates the problem. This is required as stated in the [contributing guidelines](https://github.com/davidjerleke/embla-carousel/blob/ee8fb629a3e6f505d0c309ade452d9cf1ce7cfa2/CONTRIBUTING.md). This issue will be closed without it.

Thanks for cooperating.

Best,
David

**Comment by davidjerleke** [comment]
@NicoPom thanks for your bug report.

Please read the bug reports section in the [contributing guidelines](https://github.com/davidjerleke/embla-carousel/blob/ee8fb629a3e6f505d0c309ade452d9cf1ce7cfa2/CONTRIBUTING.md#bug-reports). Your bug report is missing crucial details and a CodeSandbox. This issue will be closed otherwise.

Thanks for cooperating.

Best
David

**Comment by zaaakher** [comment]
Hey @NicoPom,

embla-carousel plugins are stand-alone packages that you have to install separately. For example:

### embla-carousel-class-names
if you want to use the `embla-carousel-class-names` plugin (developed by @davidjerleke), you'll have to install it (see [docs](https://www.embla-carousel.com/plugins/class-names/))
And since the plugin component is [exported by default](https://github.com/davidjerleke/embla-carousel/blob/master/packages/embla-carousel-class-names/src/index.ts), you simply import it like this:
```js
import ClassNames from 'embla-carousel-class-names'
```

If you want to import the types as well:
```js
import ClassNames, {
  ClassNamesOptionsType,
  ClassNamesType
} from 'embla-carousel-class-names'
```

### embla-carousel-wheel-gestures

This plugin is developed by @xiel and the source-code can be found [here](https://github.com/xiel/embla-carousel-wheel-gestures). There are no default exports, so you'll have to import it like so:

```js
import {
  WheelGesturesPlugin, //The main plugin component
  WheelGesturesPluginOptions, //The options type
} from "embla-carousel-wheel-gestures";
```

**Comment by NicoPom** [comment]
> Hey @NicoPom,
> 
> embla-carousel plugins are stand-alone packages that you have to install separately. For example:
> ### embla-carousel-class-names
> 
> if you want to use the `embla-carousel-class-names` plugin (developed by @davidjerleke), you'll have to install it (see [docs](https://www.embla-carousel.com/plugins/class-names/)) And since the plugin component is [exported by default](https://github.com/davidjerleke/embla-carousel/blob/master/packages/embla-carousel-class-names/src/index.ts), you simply import it like this:
> 
> ```js
> import ClassNames from 'embla-carousel-class-names'
> ```
> 
> If you want to import the types as well:
> 
> ```js
> import ClassNames, {
>   ClassNamesOptionsType,
>   ClassNamesType
> } from 'embla-carousel-class-names'
> ```
> 
> ### embla-carousel-wheel-gestures
> 
> This plugin is developed by @xiel and the source-code can be found [here](https://github.com/xiel/embla-carousel-wheel-gestures). There are no default exports, so you'll have to import it like so:
> 
> ```js
> import {
>   WheelGesturesPlugin, //The main plugin component
>   WheelGesturesPluginOptions, //The options type
> } from "embla-carousel-wheel-gestures";
> ```

Oh that's what I was talking about ! Sorry I wasn't very clear.
That's the solution I was looking for : thank you :) 
So it was more of a lack of knowledge of Javascript from my part.
