### ISSUE TITLE
[Bug]: iOS Stutter

### ISSUE THREAD

**Issue by WilliamWelsh** [davidjerleke/embla-carousel#890]
### Which variants of Embla Carousel are you using?

- [ ] embla-carousel **(Core)**
- [X] embla-carousel-react
- [ ] embla-carousel-vue
- [ ] embla-carousel-svelte
- [ ] embla-carousel-autoplay
- [ ] embla-carousel-auto-scroll
- [ ] embla-carousel-solid
- [ ] embla-carousel-auto-height
- [ ] embla-carousel-class-names
- [ ] embla-carousel-fade
- [ ] embla-carousel-docs **(Documentation)**
- [ ] embla-carousel-docs **(Generator)**

### Steps to reproduce

The bug occurs when I use `caoursel.scrollTo(index, false)` to smoothly scroll to the selected item.

### Expected Behavior

It should scroll smoothly on iOS browsers as it does as non-Safari browsers.

### Additional Context

I believe it has something to do with Safari/webkit.

On Android Chrome, it is perfectly smooth.
On MacOS Chrome, it is perfectly smooth.
On MacOS Safari, it stutters.
On iOS Safari, it stutters.
On iOS Chrome (which is still WebKit), it stutters.

### What browsers are you seeing the problem on?

Safari

### Version

8.1.3

### CodeSandbox

https://codesandbox.io/p/sandbox/silly-haze-3evud?file=%2Findex.html

### Before submitting

- [X] I've made research efforts and searched the documentation
- [X] I've searched for existing issues
- [X] I agree to follow this project's Contributing Guidelines for bug reports

**Comment by davidjerleke** [comment]
@WilliamWelsh thanks. While I appreciate the effort, I get issues or questions like this once in a while where the dev in question says they see stuttering. It’s really hard for me to do anything about this when I don’t see any stuttering on Safari whether I test it on my own iOS and OSX devices. Do you have anything else to add that could support your claim or help me reproduce this?

**Comment by WilliamWelsh** [comment]
If you increase the duration prop, it's easier to notice. Chrome (exlcuding Chrome iOS) it feels like butter, but every WebKit device/browser I've tried (even on embla-carousel.com) I can notice stutter.

**Comment by davidjerleke** [comment]
@WilliamWelsh have you tried well known CSS tricks to promote the container to a separate layer? Example:

```css
.embla__container {
  backface-visibility: hidden;
}

/* If that doesn’t work, try this instead (not both): */

.embla__container {
  will-change: transform;
}
```

Does that affect the animation in any way?

**Comment by WilliamWelsh** [comment]
It seems to be a lot better with the backface-visibility setting, combined with changing the duration to 10 the animation is so fast that you can't really notice it anymore

**Comment by sarussss** [comment]
Hi @davidjerleke 
It seems that when using css animation, in low power mode on iphone there is no stutter like with js animation.

**Comment by davidjerleke** [comment]
@sarussss which did you test the first one [Test1](https://dk2xgk.csb.app/)?

**Comment by sarussss** [comment]
@davidjerleke yeah, I checked on [Test 1](https://dk2xgk.csb.app/)

**Comment by sarussss** [comment]
@davidjerleke I just checked about 30 minutes ago

**Comment by davidjerleke** [comment]
@sarussss sorry to ask you but could you try [Test1](https://dk2xgk.csb.app/) once more? Both default and low battery mode and see if there's stuttering going on? I made some changes like 20 minutes ago.

**Comment by sarussss** [comment]
@davidjerleke I just checked it.
**Default mode:** There is no difference between css and js animation.
**Low battery mode:** js animation is still a bit slower than css, but it seems to reduce stuttering.

**Comment by davidjerleke** [comment]
@sarussss thanks. What device did you test on?

**Comment by sarussss** [comment]
@davidjerleke I use Iphone 15 Pro to test.

**Comment by davidjerleke** [comment]
@sarussss thanks! I also tested both on iPhone and MacBook Pro and I couldn’t reproduce any stutter when triggering the JS example, even with low power mode active. However, the JS animation is just slightly longer (but still not stuttering). When you say this:

> **Low battery mode**: js animation is still a bit slower than css, but it seems to reduce stuttering.

Do you mean that the JS animation is slower only or also stuttering?

**Comment by sarussss** [comment]
I think is still stuttering, but the stuttering has improved.
https://youtube.com/shorts/anKVGukcSNQ?si=hEyE2H7-3Uohlyaz

**Comment by davidjerleke** [comment]
@sarussss thanks for sharing the screen recording. Watching it, I think both stutter (which is expected and makes sense because it’s low battery mode after all), and it seems like the JS animation only stutters slightly more than the CSS animation (the difference is barely noticeable). Do you agree?

**Comment by WilliamWelsh** [comment]
It's definitely noticeable by a lot of people, which is why I opened the issue

**Comment by davidjerleke** [comment]
@WilliamWelsh, first off, the [Test](https://dk2xgk.csb.app/) sandbox **has changed** since you were here the last time because **I've updated it**. The JS animation there **doesn't use the same animation technique** as the current version of **Embla Carousel**. 

Secondly, @sarussss wrote this:

> **Default mode**: There is no difference between css and js animation.
> **Low battery mode**: js animation is still a bit slower than css, but it seems to reduce stuttering. 

My test results are aligned with what @sarussss wrote above, with the exception that I can barely even notice a difference between the CSS and JS animation when low battery mode is activated. But watching @sarussss screen recording, the CSS animation stutters too. So the difference isn't big by any means. 

And the whole point of low power mode is to save battery.  Even native apps can stutter. So if the CSS and JS animation is just as smooth in this [Test](https://dk2xgk.csb.app/) when the battery is loaded, and there's just a slight difference of how much they stutter between the CSS and JS animation in low power mode, I think the approach could be a candidate which could make it to the main library.

@WilliamWelsh I think this is rude:

> It's definitely noticeable by a lot of people, which is why I opened the issue

As I mentioned, [Test](https://dk2xgk.csb.app/) sandbox **has changed** since you were here the last time. The stuttering @sarussss mentioned is in **low power mode** so that doesn't even support your claim about stuttering on webkit browsers. At least not when the battery is loaded.

I'm maintaining this on my spare time so if you don't respect that and you don't have anything constructive to say just don't say anything? How are you "a lot of people"? **The whole point of this conversation** is for me to outline what choices I have moving forward, and the pros and cons of the options I have to solve/improve the animation smoothness. **The point is not** to read repeating comments that doesn't add any value to this conversation.

**Comment by WilliamWelsh** [comment]
Not sure why you took my sentence so negatively, I was just saying it (the library in its current state's sutter) was noticeable by a lot of people (only on webkit browsers, regardless of low battery mode) because a lot of people have noticed it on my site, and I am in the camp that it's not that noticeable and doesn't matter, and only opened an issue after people brought it up. Why are you jumping to me not have respect for your spare time? I'm only today catching up on this thread? I opened an issue about an issue I have? Not sure if there is some deeper problem here or something, you need to seriously take a chill pill man ☠️ I appreciate you and your library, and not sure why you crashed out from that comment. I'll go ahead and close this

**Comment by sarussss** [comment]
Hi @davidjerleke 
Totally agree with you, hope you bring these improvements to Embla, so I can test on Embla when swiping, when swiping it will often be more jerky.

**Comment by davidjerleke** [comment]
Thanks @sarussss!

I will definitely see how I can improve the animation engine. Thanks for taking the time to discuss this and sharing useful information like screen recordings and similar.

**Comment by davidjerleke** [comment]
After investigating this further, I was lucky and found that there was some iOS stutter on very specific carousel sizes and when a carousel has more than 8 slides which is weird. These two things got rid of the iOS stutter for me:

1. The internal interpolation math for the carousel animation was slightly off. It has been fixed in the following **PR**: #933. More specifically [here](https://github.com/davidjerleke/embla-carousel/pull/933/files#diff-204e39eec44543ffbc1806f72da44a8521a61c8d93ff616eecf77d9a105253f6R193-R194) in the code. The fix was released in `v8.1.7`. 

2. This is something devs have to do themselves: Add the following CSS `transform: translate3d(0, 0, 0);` to all slides. A fix for this was added to the docs in the [following commit](https://github.com/davidjerleke/embla-carousel/commit/aa6f7eb2ea4c09dc7ae0d46704a959e9d285c64b).

**Comment by davidjerleke** [comment]
@sarussss I’ve also investigated the low battery/battery saving mode and this is my answer:

Embla has a JavaScript spring animation engine that handles the animations instead of simple CSS easings. This means that the animations are done with JavaScript and more specifically with `requestAnimationFrame`. There are numerous advantages with spring based animations and if you want to really understand the benefits of this design choice, I suggest you check these out:

- Spring animations [talk](https://developer.apple.com/videos/play/wwdc2018/803/) by Apple developers
- [This article](https://medium.com/kaliberinteractive/how-i-transitioned-from-ease-to-spring-animations-5a09eeca0325) that explains the difference between spring animations and CSS easings.

However, the main downside of spring animations with JavaScript compared to CSS easing transitions is the degraded performance when low battery mode is active. This happens because unfortunately, iOS and some other devices throttle `requestAnimationFrame` heavily when low battery mode is active. The penalty is actually insane compared to CSS animations. But this is happening on a browser native level. I can’t do anything about it.

With that said, this doesn’t mean that CSS easing transitions should be preferred because of the low battery performance reduction that some browsers apply to JavaScript animations. I think the benefits of spring animations with JavaScript still outweigh simple CSS easings (please at least read the article to understand why). And when I built the Embla core, I didn’t want to build yet another carousel library with CSS easings like almost all other libraries use. They feel stiff like you’re moving around a refrigerator or huge stone. I wanted to build a solid and robust spring based carousel library with animations that feel natural.

I don’t really understand this design choice (the JavaScript animation throttling) and the reasons behind it. If the purpose is to save battery, I think it still doesn’t make much sense, because there are multiple ways to destroy the battery without using `requestAnimationFrame`. Just look at the LinkedIn and Instagram website: Both kill your battery in no time. Especially the LinkedIn website freezes as soon and you interact with it and drains your battery. 

One could argue that the battery saving mode is called so because of a reason. Performance restrictions should be expected, both when using a browser and even native apps. But still, I think the level of performance restrictions is way too high.

So if you or someone else reading this l want to try do anything about this, please create a [new WebKit bug](https://bugs.webkit.org/enter_bug.cgi) and share the link so anyone else that sees this can go to the bug report and add a +1 to it to show that it troubles more than one person.

**Comment by Forsect** [comment]
Hey @davidjerleke 

First of all sorry for digging up old thread, but I believe it’s the best place for it, given that the issue was no **_truly_** resolved. I started to use your carousel and lucky me ofc ai have performance issue, even without the low battery mode, still trying to find out why but in the meantime I found this issue and yes - I strongly believe the spring animations are the way to go, yet I don’t relate to your conclusion that we need to use JS - well we don’t:

https://developer.chrome.com/docs/css-ui/css-linear-easing-function

https://github.com/jakearchibald/linear-easing-generator

https://linear-easing-generator.netlify.app/

I am using it with great success in my tailwind-css project for all my other spring animations, and believe me, there is a ton of them. So while I’m working on to find out my issue, I was hoping you could check it out, and maybe even implement it, so maybe, just maybe, my issue would be resolved automatically 😁

Cheers

**Comment by davidjerleke** [comment]
@Forsect you will find an answer to [your comment](https://github.com/davidjerleke/embla-carousel/issues/890#issuecomment-2677138100) here:

- https://github.com/davidjerleke/embla-carousel/discussions/1141#discussioncomment-12448923

**Comment by davidjerleke** [comment]
@Forsect Just to help narrow things down—what device are you noticing the stutter on?

**Comment by Forsect** [comment]
@davidjerleke Sorry, didn't see the message :x Well, all of them. iPhone 16 Pro Max, MBP M3 MAX, all browsers.

**Comment by davidjerleke** [comment]
@Forsect Could you please provide something more concrete that I can work with? A screen recording and a CodeSandbox setup where the issue occurs would be really helpful. Also, does the stutter happen when dragging, or when the animation is triggered by the navigation buttons, or both?

**Comment by JudithGo** [comment]
I have problems with iphone 11 ios 16.4 and some other models.

**Comment by davidjerleke** [comment]
@JudithGo I’d really appreciate it if we could keep things concrete. It’s hard for me to help when claims are made without any supporting detail. If you’re experiencing stuttering and would like me to look into it, please share a CodeSandbox with a reproducible example of your setup so I have something to work with.

Thanks.

**Comment by JudithGo** [comment]
> [@JudithGo](https://github.com/JudithGo) I’d really appreciate it if we could keep things concrete. It’s hard for me to help when claims are made without any supporting detail. If you’re experiencing stuttering and would like me to look into it, please share a CodeSandbox with a reproducible example of your setup so I have something to work with.
> 
> Thanks.

Sure, here it is: https://stackblitz.com/edit/stackblitz-starters-pjh4xvxt?file=app%2Fpage.tsx

**Comment by davidjerleke** [comment]
Hi @JudithGo,

The stuttering issue disappeared after I removed the following:

```diff
          <CarouselSlide>
            <Image
-            className="relative dark:drop-shadow-[0_0_0.3rem_#ffffff70] dark:invert"
+            className="relative dark:invert"
              src="/next.svg"
              alt="Next.js Logo"
              width={180}
              height={37}
              priority
            />
          </CarouselSlide>
```

Drop shadows applied via the filter CSS property are known to negatively impact performance — especially on complex elements like modals or carousels. They even cause stuttering during CSS animations.

That said, I noticed a more significant performance concern in your setup: there are literally 1000 carousels on the page, and every slide uses `transform: translate3d(0, 0, 0)`. While GPU acceleration can be helpful, applying it too broadly creates an overwhelming number of GPU layers, which actually hurts performance rather than improving it.

**Suggestion:** Consider removing `transform: translate3d(0, 0, 0)` from slides in carousels that are not currently in view. This way, only the active carousel benefits from GPU acceleration, keeping performance optimized.

Also, this CSS:

```css
.carousel_blur_move {
  mask-image: linear-gradient(
    to right,
    rgba(0, 0, 0, 0.5) 0%,
    rgba(0, 0, 0, 1) 15%,
    rgba(0, 0, 0, 1) 85%,
    rgba(0, 0, 0, 0.5) 100%
  );
}
```

...may cause the browser to perform heavy calculations as the carousel scrolls — especially on lower-end devices — since mask-image is a relatively expensive visual effect. If possible, consider an alternative approach that achieves a similar visual result with less performance overhead (e.g. using a static gradient overlay or fading edges with pseudo-elements).

**Comment by EmilyRight** [comment]
hi @davidjerleke! Thank you for your awesome library) and for your last comment - 'Drop shadows applied via the filter CSS property are known to negatively impact performance — especially on complex elements like modals or carousels". Applying will-change: filter to all filtered elements inside embla-cards fixed freezes for me on iOS)
