### ISSUE TITLE
[Bug]: Jitter on resize when not on first image

### ISSUE THREAD

**Issue by vincvdwal** [davidjerleke/embla-carousel#905]
### Which variants of Embla Carousel are you using?

- [X] embla-carousel **(Core)**
- [ ] embla-carousel-react
- [X] embla-carousel-vue
- [ ] embla-carousel-svelte
- [ ] embla-carousel-autoplay
- [ ] embla-carousel-auto-scroll
- [ ] embla-carousel-solid
- [ ] embla-carousel-auto-height
- [ ] embla-carousel-class-names
- [ ] embla-carousel-fade
- [ ] embla-carousel-docs **(Documentation)**
- [ ] embla-carousel-docs **(Generator)**

### Steps to reproduce

- Initialize a embla-carousel with more then 2 images
- Go to > 2nd image
- Resize window
[jitter.webm](https://github.com/davidjerleke/embla-carousel/assets/111272374/e8b42ee5-7416-42d4-9348-273d074e705f)

### Expected Behavior

On resizing the window, the carousel image should resize smoothly

### Additional Context

Apparently, the first image resizes perfectly, only occurs from the second image onwards

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari

### Version

v8.1.4

### Before submitting

- [X] I've made research efforts and searched the documentation
- [X] I've searched for existing issues
- [X] I agree to follow this project's Contributing Guidelines for bug reports

**Comment by davidjerleke** [comment]
@vincvdwal this is because Embla doesn’t know the carousel container element size beforehand when it changes. It needs to get the new dimensions after a resize and adjust its position based on the new dimensions. That’s why it takes a very brief moment before it positions itself correctly.

You don’t resize the window slowly when using a real world application (at least if you’re not a developer). Most visitors will never even trigger a resize. If they do, it’s probably when they change orientation on a tablet or mobile which will trigger a single resize. And in these cases, it won’t be a problem and it’s negligible.

**Comment by silllli** [comment]
I’ve built an interface with a resize slider. You can drag its handle to resize the elements on the page (including Embla Carousel instances). The jumping of the slides while dragging the slider was a big problem.

But: I found a great workaround. I wrote this custom resize callback which will move the current slide to the front (since we know that there won’t be any jumping going on) and instantly scroll the carousel to the first slide.

```javascript
const currentSlides = [slide1, slide2, slide3];

function shiftToFront(array, n) {
  return [...array.slice(n), ...array.slice(0, n)];
}

function handleResize(emblaApi) {
  // get the currently selected slide
  const currentIndex = emblaApi.selectedScrollSnap();

  // shift the slide array so the currently selected slide is in the front
  currentSlides = shiftToFront(currentSlides, currentIndex);

  // let the carousel jump to the first slide
  emblaApi.scrollTo(0, true);

  // let embla handle resizing as usual
  return true;
}
```

I’m using a reactive framework, so the HTML will instantly update when changing my `currentSlides` variable.

**Comment by davidjerleke** [comment]
@silllli and/or @vincvdwal feel free to investigate the core Embla code and see if you can improve the resize jitter if you think it's important.

Best,
David

**Comment by davidjerleke** [comment]
Proof of buggy behavior provided in:

- #924

**Comment by davidjerleke** [comment]
@vincvdwal @silllli @joacoespinosa, 

The resize jitter was introduced when fixing this problem:

- #488

But I found a way around it that solves both problems. The bug fix will be released in the next version `v8.1.8`.

**Comment by silllli** [comment]
@davidjerleke Yes, fixes the problem I encountered! Thank you!

**Comment by davidjerleke** [comment]
@silllli thanks for taking time to confirm 👍🏻.

**Comment by vincvdwal** [comment]
@davidjerleke Are the released changes immediately effective on the https://www.embla-carousel.com/ example page? I had trouble finding versioning there. What I noticed that the jitter greatly (almost non-existing at this point) improved on resizing to a smaller window. But the jitter remains on resizing the screen / window to a bigger size.

**Comment by davidjerleke** [comment]
@vincvdwal that depends on which examples you mean. Which ones did you test?

**Comment by vincvdwal** [comment]
Basically all of them have it, but with the ones with images it's the most apparent. Also note that the first slide is often fine, it's from the second slide onward.

**Comment by vincvdwal** [comment]
There it seem to work nicely. Thanks!

**Comment by davidjerleke** [comment]
@vincvdwal it could be cache related. I don’t have access to my computer for two day from now so I can’t look into it though
