### ISSUE TITLE
[Bug]: canScrollPrev() and canScrollNext() struggle with dragFree: true

### ISSUE THREAD

**Issue by kbachl** [davidjerleke/embla-carousel#938]
### Which variants of Embla Carousel are you using?

- [X] embla-carousel **(Core)**
- [ ] embla-carousel-react
- [ ] embla-carousel-vue
- [ ] embla-carousel-svelte
- [ ] embla-carousel-autoplay
- [ ] embla-carousel-auto-scroll
- [ ] embla-carousel-solid
- [ ] embla-carousel-auto-height
- [ ] embla-carousel-class-names
- [ ] embla-carousel-fade
- [ ] embla-carousel-docs **(Documentation)**
- [ ] embla-carousel-docs **(Generator)**

### Steps to reproduce

See this Sandbox, generated from the Embla Generator with dragFree, 33% and Group Slides:
https://codesandbox.io/s/jy5xck?file=/index.html
If you open it up in Firefox or Chrome and drag exactly 1 slide, the "Next" button gets deactivated, yet we only see slides 2 to 4.
If we go to Slide 5 and scroll back slowly to see slides 2 to 4 it happens with the prev.
It seems that if the remaining slides are lower than the slides you usually scroll (here 3) it gets greyed out, yet there are hidden slides left that can only be reached by drag then.

### Expected Behavior

Prev and Next need to be active till they are at the END or the START slides, e.g. index = 0 or index = maxIndex

### Additional Context

I have also tried...

### Version

8.1.6

### CodeSandbox

https://codesandbox.io/s/jy5xck

### Before submitting

- [X] I've made research efforts and searched the documentation
- [X] I've searched for existing issues
- [X] I agree to follow this project's Contributing Guidelines for bug reports

**Comment by davidjerleke** [comment]
Hi @kbachl,

Thanks for your bug report. This is by design and I'm going to try to explain why. When you group slides in your CodeSandbox example, Embla treats every group of slides as if it were a single slide. In your case:

<img width="526" alt="slide-1" src="https://github.com/user-attachments/assets/e39abfdb-4874-4b9a-8129-729f988e57e9">

<img width="523" alt="slide-2" src="https://github.com/user-attachments/assets/69148656-6357-43e9-980b-a7de24e63582">

Your setup has **two scroll snaps** because you group your slides:

- **A:** Scroll snap **A** includes [slide 1, slide 2, slide 3]
- **B:** Scroll snap **B** includes [slide 4, slide 5]

Now the `canScrollPrev()` and `canScrollNext()` methods are purely based on scroll snap **index** and not if the carousel has scrolled to any end or not (i.e. fully to the left or right). Nor is it based on what slides are visible or not. Any time you scroll the carousel with drag free, `canScrollPrev()` and `canScrollNext()` will check if the current carousel position is closest to snap `A` or `B`. If the position where the carousel stops after dragging is closest to snap `B`, `canScrollPrev()` will return `true`. If it's closest to snap `A`, `canScrollNext()` will return `true`. 

Of course, one could argue that `canScrollPrev()` and `canScrollNext()` should be purely based on if the has scrolled to any end or not. But in that case, it's a feature/change request. Not a bug. I could create a poll for devs to vote about this change, but the problem I have is that I've created similar polls about features before, and after a year has gone by, I've only gathered like 35 votes or something. It's not much if we were to make a decision based on that.

With that said, you can use the `emblaApi.internalEngine()` to create your own `canScrollPrev()` and `canScrollNext()` methods to achieve what you want.

Best,
David

**Comment by davidjerleke** [comment]
@kbachl have you read my [comment](https://github.com/davidjerleke/embla-carousel/issues/938#issuecomment-2231739518)?

**Comment by kbachl** [comment]
Hi @davidjerleke,
sorry for beeing late :)

I understand what you mean and why you dont see it as a bug, yet I'm still a bit troubled because it's - simply spoken - code generated by your carousel generator that is not working as one would expect it. 

I haven't had time to dig into `emblaApi.internalEngine()` since I usually try to stay miles away from "internal" parts of libraries, but I at least would like to have this issue added to the documentation. 
In my point of view code that gets generated by a promoted generator has to work like the end-user expects it.

And thanks for taking your time on helping me here and I really must admit that the current embla carousel is way better than the "keen-slider" it has replaced. Very smoth and with the way it gets integrated exactly 0 CLS.

**Comment by davidjerleke** [comment]
@kbachl thanks for your response.

> I understand what you mean and why you dont see it as a bug, yet I'm still a bit troubled because it's - simply spoken - code generated by your carousel generator that is not working as one would expect it.

When you say "is not working as one would expect it" we should be clear that it's how **you expect** it to work. The current behavior is by design and expected. It's not a bug. As I explained in my [previous comment](https://github.com/davidjerleke/embla-carousel/issues/938#issuecomment-2231739518), the `canScrollPrev()` and `canScrollNext()` methods are purely based on scroll snap index and not if the carousel has scrolled to any end or not, meaning fully to the left or right end.

Embla has been around for a long time, even before keen-slider and this is the first time someone wants to change the current behavior. I can't change the carousel behavior based on a single developers opinion but I can promise this: If a lot of devs come here and give your issue thumbs up and complain about this, I will consider changing the internal behavior. But until then, I've put together a `canScrollBackward()` and `canScrollForward()` function in this [CodeSandbox](https://codesandbox.io/p/sandbox/embla-carousel-generator-vanilla-forked-7zwdk6?file=%2Fsrc%2Fjs%2FEmblaCarouselArrowButtons.js%3A1%2C1-11%2C2) that does what you want.

Best,
David
