### ISSUE TITLE
[Bug]: Even amount of items per slide

### ISSUE THREAD

**Issue by alvinnnnn21** [davidjerleke/embla-carousel#982]
### Which variants of Embla Carousel are you using?

- [X] embla-carousel **(Core)**
- [X] embla-carousel-react
- [ ] embla-carousel-vue
- [ ] embla-carousel-svelte
- [ ] embla-carousel-autoplay
- [ ] embla-carousel-auto-scroll
- [ ] embla-carousel-solid
- [ ] embla-carousel-auto-height
- [ ] embla-carousel-class-names
- [ ] embla-carousel-fade
- [ ] embla-carousel-docs **(Documentation)**
- [ ] embla-carousel-docs **(Generator)**

### Steps to reproduce

I tried to set my slide size to 50% width so that each slide will contain onky 2 items, but when the slide play / or i press next / drag the next slide the next slide will got cut off and only will show full item when i reach end of the items. This only occurs everytime i set to even amout of items per slide. I am sure if this is a bug or is it itended to behave this way.

### Expected Behavior

Show full slide items on every amount of items per slide.

### Additional Context

I have also tried...

### What browsers are you seeing the problem on?

Chrome

### Before submitting

- [X] I've made research efforts and searched the documentation
- [X] I've searched for existing issues
- [X] I agree to follow this project's Contributing Guidelines for bug reports

**Comment by davidjerleke** [comment]
@alvinnnnn21 please create a CodeSandbox demonstrating the problem. This is most likely a faulty setup on your side and if you’re looking for guidance it’s recommended to create a [discussion](https://github.com/davidjerleke/embla-carousel/discussions/new?category=help) instead.

**Comment by alvinnnnn21** [comment]
i am sorry, still new with this kind of stuff. 

here is the codepen to demonstrated my problem.

https://codesandbox.io/p/sandbox/carousel-qtky2c

**Comment by alvinnnnn21** [comment]
Hi @sarussss, i tried your suggestion and it works !! Thank you so much for the suggestion, can you help me to understand why does changing the alignment to start make it work ?

**Comment by davidjerleke** [comment]
Hi @alvinnnnn21,

This is because the `align` option controls how you want to align your scroll snaps relative to the viewport. Read about it in the docs:

- [align](https://www.embla-carousel.com/api/options/#align)

If you want a visual demonstration of the align property, use the [carousel generator](https://www.embla-carousel.com/examples/generator/) and set the slide size to 50%. After that you can change the `align` option, scroll back and forth and se what it does.

And a friendly reminder, please create a new [discussion](https://github.com/davidjerleke/embla-carousel/discussions/new?category=help) if you need help. Just because the carousel isn’t behaving exactly as you would like, it doesn’t automatically mean that it’s a bug. Thanks for cooperating!

**Comment by alvinnnnn21** [comment]
@davidjerleke Yeah, sorry about that—it was my mistake. Thanks for taking your time.
